import { chromium } from "playwright";
const APP=process.env.APP ?? "https://zhxinyue29.github.io/peerproof";
const b = await chromium.launch();
const p = await (await b.newContext({viewport:{width:1500,height:1000},deviceScaleFactor:2,locale:"zh-CN"})).newPage();
await p.addInitScript(()=>localStorage.setItem("peerproof.lang","zh"));
await p.goto(APP+"/",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(4500);
await p.screenshot({path:"/tmp/home-now.png",fullPage:true});
console.log((await p.evaluate(()=>document.body.innerText)).replace(/\n+/g," ").slice(0,320));
await b.close();
