import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
await ctx.addInitScript(() => localStorage.setItem("peerproof.lang", "zh"));
const p = await ctx.newPage();
await p.goto("https://zhxinyue29.github.io/peerproof/me/?v=" + Date.now(), { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
await p.screenshot({ path: process.argv[2] + "/线上-我的证明.png" });
console.log("标题:", await p.locator('h1').first().innerText().catch(()=>"(无)"));
await b.close();
