import { chromium } from "playwright";
const [u,o,w,h] = process.argv.slice(2);
const b = await chromium.launch();
const c = await b.newContext({ viewport:{width:+w,height:+h}, deviceScaleFactor:2 });
await c.addInitScript(()=>localStorage.setItem("peerproof.lang","zh"));
const p = await c.newPage();
await p.goto(u,{waitUntil:"networkidle",timeout:60000}).catch(()=>{});
await p.waitForTimeout(2000);
await p.screenshot({path:o,fullPage:true});
await b.close();
