// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title AttendanceEscrow
/// @notice Event deposit escrow settled by peer attestation instead of organizer check-in.
///
/// Attendees stake a deposit to register. At the venue, they attest to each other by scanning
/// short-lived codes: each code is an ECDSA signature over (eventId, subject, epoch) produced by
/// a key the attendee derived from their passkey's WebAuthn PRF output. A single scan credits
/// both parties, so a room of N people reaches quorum in O(N) transactions.
///
/// Every attestation must also carry a fresh signature from the venue beacon — a display at the
/// venue holding an ephemeral key. That forces the submitter to have been in the room. And since
/// being confirmed requires having submitted at least one attestation yourself, everyone who
/// settles as present was physically there, not just relayed in by a friend.
///
/// Once the window closes, attendees confirmed present reclaim their deposit and split the
/// deposits forfeited by no-shows. The organizer can never release, withhold, or receive
/// deposits. Organizer check-in exists only as a fallback and unlocks only when the room was too
/// small for peers to establish quorum on their own.
contract AttendanceEscrow {
    /* ---------------------------------------------------------------------- */
    /*                                 Types                                  */
    /* ---------------------------------------------------------------------- */

    enum Status {
        Open, // accepting registrations
        Cancelled, // quorum not met, or nobody could be confirmed; deposits refundable
        Settled // window closed and payouts locked in
    }

    struct Event {
        address organizer;
        address beaconKey; // venue display's ephemeral key; signs the beacon codes
        uint96 deposit; // per-attendee stake, in wei
        uint32 capacity; // max registrations
        uint32 minQuorum; // registrations required for the event to run at all
        uint8 k; // attestations required to be confirmed present
        uint64 registerDeadline;
        uint64 attestOpen;
        uint64 attestClose;
        Status status;
        uint32 registered;
        uint32 peerConfirmed; // confirmed via peer attestation alone
        uint32 orgConfirmed; // confirmed via the organizer fallback
        uint256 sharePerAttendee; // set at settle(): deposit + cut of the forfeited pool
    }

    /* ---------------------------------------------------------------------- */
    /*                                 Storage                                */
    /* ---------------------------------------------------------------------- */

    uint256 public nextEventId = 1;

    /// @dev Read via `getEvent`. Kept internal because a 14-field autogenerated getter blows
    ///      the stack limit without via-ir.
    mapping(uint256 => Event) internal _events;

    /// @dev eventId => attendee => registered
    mapping(uint256 => mapping(address => bool)) public isRegistered;
    /// @dev eventId => attendee => address recovered from their rotating codes
    mapping(uint256 => mapping(address => address)) public attestKeyOf;
    /// @dev eventId => attendee => attestations received
    mapping(uint256 => mapping(address => uint32)) public attestCount;
    /// @dev eventId => attendee => attestations they submitted themselves. Non-zero is proof they
    ///      held a fresh venue beacon, i.e. that they were in the room.
    mapping(uint256 => mapping(address => uint32)) public gaveCount;
    /// @dev eventId => attendee => confirmed present
    mapping(uint256 => mapping(address => bool)) public isConfirmed;
    /// @dev eventId => attendee => payout already withdrawn
    mapping(uint256 => mapping(address => bool)) public hasClaimed;
    /// @dev eventId => keccak(low, high) => that unordered pair has already attested once
    mapping(uint256 => mapping(bytes32 => bool)) public pairUsed;

    /// @notice Attendee rotating codes are valid for this many seconds.
    uint256 public constant EPOCH = 15;

    /// @notice Venue beacon codes rotate on this slower cadence, so an attendee does not have to
    ///         re-read the venue display every few seconds.
    uint256 public constant BEACON_EPOCH = 120;

    /// @notice Grace period after the attestation window during which the organizer fallback may
    ///         still run. Settlement is blocked until it elapses, but only for rooms that
    ///         actually need the fallback — otherwise anyone could settle the instant the window
    ///         shut and strand the few people who did show up.
    uint256 public constant FALLBACK_WINDOW = 1 hours;

    /* ---------------------------------------------------------------------- */
    /*                                 Events                                 */
    /* ---------------------------------------------------------------------- */

    event EventCreated(
        uint256 indexed eventId,
        address indexed organizer,
        uint96 deposit,
        uint32 capacity,
        uint32 minQuorum,
        uint8 k,
        uint64 registerDeadline,
        uint64 attestOpen,
        uint64 attestClose
    );
    event BeaconKeySet(uint256 indexed eventId, address beaconKey);
    event Registered(uint256 indexed eventId, address indexed attendee, address attestKey);
    event Attested(uint256 indexed eventId, address indexed attester, address indexed subject, uint64 epoch);
    event Confirmed(uint256 indexed eventId, address indexed attendee, bool viaOrganizer);
    event EventCancelled(uint256 indexed eventId, uint32 registered, uint32 minQuorum);
    event Settled(uint256 indexed eventId, uint32 confirmed, uint32 noShows, uint256 sharePerAttendee);
    event Claimed(uint256 indexed eventId, address indexed attendee, uint256 amount);

    /* ---------------------------------------------------------------------- */
    /*                                 Errors                                 */
    /* ---------------------------------------------------------------------- */

    error BadParams();
    error NoSuchEvent();
    error WrongStatus();
    error DeadlinePassed();
    error AtCapacity();
    error AlreadyRegistered();
    error NotRegistered();
    error WindowClosed();
    error WindowOpen();
    error SelfAttestation();
    error PairAlreadyUsed();
    error StaleCode();
    error BadCode();
    error StaleBeacon();
    error BadBeacon();
    error NotOrganizer();
    error FallbackLocked();
    error FallbackPending();
    error QuorumMet();
    error QuorumNotMet();
    error NothingToClaim();
    error AlreadyClaimed();
    error TransferFailed();

    /* ---------------------------------------------------------------------- */
    /*                              Event setup                               */
    /* ---------------------------------------------------------------------- */

    /// @notice Create an event. The organizer sends no funds and can never withdraw any.
    /// @param beaconKey Address of the key held by the venue display.
    function createEvent(
        address beaconKey,
        uint96 deposit,
        uint32 capacity,
        uint32 minQuorum,
        uint8 k,
        uint64 registerDeadline,
        uint64 attestOpen,
        uint64 attestClose
    ) external returns (uint256 eventId) {
        if (deposit == 0 || capacity == 0 || k == 0) revert BadParams();
        if (beaconKey == address(0)) revert BadParams();
        if (minQuorum == 0 || minQuorum > capacity) revert BadParams();
        // A room needs at least k+1 people for peers to reach quorum without the fallback.
        if (minQuorum <= k) revert BadParams();
        if (registerDeadline <= block.timestamp) revert BadParams();
        if (attestOpen < registerDeadline || attestClose <= attestOpen) revert BadParams();

        eventId = nextEventId++;
        Event storage e = _events[eventId];
        e.organizer = msg.sender;
        e.beaconKey = beaconKey;
        e.deposit = deposit;
        e.capacity = capacity;
        e.minQuorum = minQuorum;
        e.k = k;
        e.registerDeadline = registerDeadline;
        e.attestOpen = attestOpen;
        e.attestClose = attestClose;
        e.status = Status.Open;

        emit EventCreated(
            eventId, msg.sender, deposit, capacity, minQuorum, k, registerDeadline, attestOpen, attestClose
        );
        emit BeaconKeySet(eventId, beaconKey);
    }

    /// @notice Replace the venue beacon key before the window opens, in case the organizer loses
    ///         the device or has to swap venues. Locked once attestation starts so it cannot be
    ///         used to invalidate attestations already in flight.
    function setBeaconKey(uint256 eventId, address beaconKey) external {
        Event storage e = _load(eventId);
        if (msg.sender != e.organizer) revert NotOrganizer();
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp >= e.attestOpen) revert WindowClosed();
        if (beaconKey == address(0)) revert BadParams();

        e.beaconKey = beaconKey;
        emit BeaconKeySet(eventId, beaconKey);
    }

    /// @notice Stake the deposit and register. `attestKey` is the address of the key derived from
    ///         the caller's passkey PRF output; it signs their rotating codes.
    function register(uint256 eventId, address attestKey) external payable {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp >= e.registerDeadline) revert DeadlinePassed();
        if (e.registered >= e.capacity) revert AtCapacity();
        if (isRegistered[eventId][msg.sender]) revert AlreadyRegistered();
        if (attestKey == address(0)) revert BadParams();
        if (msg.value != e.deposit) revert BadParams();

        isRegistered[eventId][msg.sender] = true;
        attestKeyOf[eventId][msg.sender] = attestKey;
        e.registered += 1;

        emit Registered(eventId, msg.sender, attestKey);
    }

    /* ---------------------------------------------------------------------- */
    /*                              Attestation                               */
    /* ---------------------------------------------------------------------- */

    /// @notice Attest that `subject` is physically present, by submitting a rotating code they
    ///         displayed together with a fresh code from the venue beacon. Credits both parties.
    /// @param code ECDSA signature by the subject's attest key over `codeDigest(...)`.
    /// @param beaconSig ECDSA signature by the venue beacon key over `beaconDigest(...)`.
    function attest(
        uint256 eventId,
        address subject,
        uint64 epoch,
        bytes calldata code,
        uint64 beaconEpoch,
        bytes calldata beaconSig
    ) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp < e.attestOpen) revert WindowOpen();
        if (block.timestamp >= e.attestClose) revert WindowClosed();
        if (subject == msg.sender) revert SelfAttestation();
        if (!isRegistered[eventId][msg.sender]) revert NotRegistered();
        if (!isRegistered[eventId][subject]) revert NotRegistered();

        // The venue code proves the submitter was in the room. Without this an attendee could
        // simply be texted a peer's signature and attest from anywhere.
        uint64 nowBeacon = uint64(block.timestamp / BEACON_EPOCH);
        if (beaconEpoch != nowBeacon && beaconEpoch + 1 != nowBeacon) revert StaleBeacon();
        if (_recoverSig(beaconDigest(eventId, beaconEpoch), beaconSig) != e.beaconKey) revert BadBeacon();

        // The subject's code must belong to the current or immediately previous epoch, so a
        // screenshot taken more than ~30s ago is useless.
        uint64 nowEpoch = uint64(block.timestamp / EPOCH);
        if (epoch != nowEpoch && epoch + 1 != nowEpoch) revert StaleCode();
        if (_recoverSig(codeDigest(eventId, subject, epoch), code) != attestKeyOf[eventId][subject]) {
            revert BadCode();
        }

        bytes32 pair = _pairKey(msg.sender, subject);
        if (pairUsed[eventId][pair]) revert PairAlreadyUsed();
        pairUsed[eventId][pair] = true;

        emit Attested(eventId, msg.sender, subject, epoch);

        attestCount[eventId][subject] += 1;
        attestCount[eventId][msg.sender] += 1;
        gaveCount[eventId][msg.sender] += 1;

        _maybeConfirm(eventId, e, subject);
        _maybeConfirm(eventId, e, msg.sender);
    }

    /// @dev Presence requires both being vouched for `k` times AND having vouched for someone
    ///      else at least once — the latter is what proves this account held a venue beacon.
    function _maybeConfirm(uint256 eventId, Event storage e, address who) private {
        if (isConfirmed[eventId][who]) return;
        if (attestCount[eventId][who] < e.k) return;
        if (gaveCount[eventId][who] == 0) return;

        isConfirmed[eventId][who] = true;
        e.peerConfirmed += 1;
        emit Confirmed(eventId, who, false);
    }

    /// @notice Fallback check-in by the organizer. Only unlocks after the window closes and only
    ///         when peers failed to establish quorum, i.e. fewer than k+1 attendees were
    ///         confirmed on their own. In a healthy room this reverts, so the organizer is
    ///         structurally unable to influence a normal settlement.
    /// @dev The organizer still cannot receive funds in any branch; the worst they can do here is
    ///      misattribute presence among addresses that already staked a deposit.
    function organizerCheckIn(uint256 eventId, address[] calldata attendees) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (msg.sender != e.organizer) revert NotOrganizer();
        if (block.timestamp < e.attestClose) revert WindowOpen();
        if (e.peerConfirmed > e.k) revert FallbackLocked();

        for (uint256 i; i < attendees.length; ++i) {
            address a = attendees[i];
            if (!isRegistered[eventId][a]) revert NotRegistered();
            if (isConfirmed[eventId][a]) continue;
            isConfirmed[eventId][a] = true;
            e.orgConfirmed += 1;
            emit Confirmed(eventId, a, true);
        }
    }

    /* ---------------------------------------------------------------------- */
    /*                               Settlement                               */
    /* ---------------------------------------------------------------------- */

    /// @notice Cancel an event whose registrations never reached `minQuorum`. Callable by anyone
    ///         once the registration deadline passes; every deposit becomes refundable.
    function cancelForQuorum(uint256 eventId) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp < e.registerDeadline) revert DeadlinePassed();
        if (e.registered >= e.minQuorum) revert QuorumMet();

        e.status = Status.Cancelled;
        emit EventCancelled(eventId, e.registered, e.minQuorum);
    }

    /// @notice Close out an event and lock in payouts. Callable by anyone once the attestation
    ///         window has passed — in production this is driven by a scheduled job, so no human
    ///         action is required and no human can withhold it.
    function settle(uint256 eventId) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp < e.attestClose) revert WindowOpen();
        if (e.registered < e.minQuorum) revert QuorumNotMet();
        // Rooms where peers reached quorum can never use the fallback, so they settle at once.
        // Everyone else waits out the grace period, or a griefer could settle at attestClose+1
        // and permanently deny the organizer the chance to check in the handful who came.
        if (e.peerConfirmed <= e.k && block.timestamp < e.attestClose + FALLBACK_WINDOW) {
            revert FallbackPending();
        }

        uint32 confirmed = e.peerConfirmed + e.orgConfirmed;
        uint32 noShows = e.registered - confirmed;

        if (confirmed == 0) {
            // Nobody could be confirmed present. Refund every deposit rather than issue an
            // unreliable verdict; the organizer captures nothing.
            e.status = Status.Cancelled;
            emit EventCancelled(eventId, e.registered, e.minQuorum);
            return;
        }

        uint256 forfeited = uint256(e.deposit) * noShows;
        e.sharePerAttendee = uint256(e.deposit) + forfeited / confirmed;
        e.status = Status.Settled;

        emit Settled(eventId, confirmed, noShows, e.sharePerAttendee);
    }

    /// @notice Withdraw whatever the caller is owed. Pull payment, so one failing recipient
    ///         cannot block anyone else.
    function claim(uint256 eventId) external {
        Event storage e = _load(eventId);
        if (!isRegistered[eventId][msg.sender]) revert NotRegistered();
        if (hasClaimed[eventId][msg.sender]) revert AlreadyClaimed();

        uint256 amount;
        if (e.status == Status.Cancelled) {
            amount = e.deposit;
        } else if (e.status == Status.Settled) {
            if (!isConfirmed[eventId][msg.sender]) revert NothingToClaim();
            amount = e.sharePerAttendee;
        } else {
            revert WrongStatus();
        }

        hasClaimed[eventId][msg.sender] = true;
        emit Claimed(eventId, msg.sender, amount);

        (bool ok,) = msg.sender.call{value: amount}("");
        if (!ok) revert TransferFailed();
    }

    /* ---------------------------------------------------------------------- */
    /*                                 Views                                  */
    /* ---------------------------------------------------------------------- */

    function getEvent(uint256 eventId) external view returns (Event memory) {
        return _events[eventId];
    }

    function confirmedCount(uint256 eventId) external view returns (uint32) {
        Event storage e = _events[eventId];
        return e.peerConfirmed + e.orgConfirmed;
    }

    function statusOf(uint256 eventId) external view returns (Status) {
        return _events[eventId].status;
    }

    /// @notice Whether the organizer fallback is currently available for this event.
    function fallbackAvailable(uint256 eventId) external view returns (bool) {
        Event storage e = _events[eventId];
        return e.status == Status.Open && block.timestamp >= e.attestClose && e.peerConfirmed <= e.k;
    }

    /// @notice The message a subject's attest key must sign for the given epoch.
    function codeDigest(uint256 eventId, address subject, uint64 epoch) public view returns (bytes32) {
        return _ethSigned(keccak256(abi.encode(address(this), eventId, subject, epoch)));
    }

    /// @notice The message the venue beacon key must sign for the given beacon epoch.
    function beaconDigest(uint256 eventId, uint64 beaconEpoch) public view returns (bytes32) {
        return _ethSigned(keccak256(abi.encode(address(this), eventId, "beacon", beaconEpoch)));
    }

    function currentEpoch() external view returns (uint64) {
        return uint64(block.timestamp / EPOCH);
    }

    function currentBeaconEpoch() external view returns (uint64) {
        return uint64(block.timestamp / BEACON_EPOCH);
    }

    /* ---------------------------------------------------------------------- */
    /*                                Internals                               */
    /* ---------------------------------------------------------------------- */

    function _load(uint256 eventId) private view returns (Event storage e) {
        e = _events[eventId];
        if (e.organizer == address(0)) revert NoSuchEvent();
    }

    function _ethSigned(bytes32 inner) private pure returns (bytes32) {
        return keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", inner));
    }

    function _pairKey(address a, address b) private pure returns (bytes32) {
        return a < b ? keccak256(abi.encodePacked(a, b)) : keccak256(abi.encodePacked(b, a));
    }

    function _recoverSig(bytes32 digest, bytes calldata sig) private pure returns (address) {
        if (sig.length != 65) revert BadCode();
        bytes32 r = bytes32(sig[0:32]);
        bytes32 s = bytes32(sig[32:64]);
        uint8 v = uint8(sig[64]);
        if (v < 27) v += 27;
        // Reject the malleable upper half of the curve order.
        if (uint256(s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) revert BadCode();
        address signer = ecrecover(digest, v, r, s);
        if (signer == address(0)) revert BadCode();
        return signer;
    }
}
