// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title AttendanceEscrow
/// @notice Event deposit escrow settled by peer attestation instead of organizer check-in.
///
/// Attendees stake a deposit to register. At the venue, they attest to each other by scanning
/// short-lived codes: each code is an ECDSA signature over (eventId, subject, epoch) produced by
/// a key the attendee derived from their passkey's WebAuthn PRF output. A single scan credits
/// both parties, so a room of N people reaches quorum in O(N) transactions.
///
/// Arriving is a separate act from attesting. Before an attendee can vouch for anyone they must
/// check in once, by submitting a fresh signature from the venue beacon — a display at the venue
/// holding an ephemeral key. The chain timestamps that transaction, so the beacon has to be live
/// at the moment of arrival, and relaying one to somebody across town means relaying it inside a
/// single beacon epoch. Since being confirmed requires having submitted at least one attestation
/// yourself, everyone who settles as present walked through the door.
///
/// Attesting deliberately carries no beacon of its own. Presence is a fact about arrival, not
/// something to be re-proved every two minutes: an earlier design demanded a live beacon on every
/// attestation, which meant you had to find, greet, and scan another person inside the beacon's
/// window or start over. The two clocks are independent, and only the arrival one is a security
/// boundary.
///
/// Once the window closes, attendees confirmed present reclaim their deposit and split the
/// deposits forfeited by no-shows. The organizer can never release, withhold, or receive
/// deposits. Organizer check-in exists only as a fallback and unlocks only when the room was too
/// small for peers to establish quorum on their own.
contract AttendanceEscrow {
    /* ---------------------------------------------------------------------- */
    /*                                 Types                                  */
    /* ---------------------------------------------------------------------- */

    enum Status {
        Open, // accepting registrations
        Cancelled, // quorum not met, or nobody could be confirmed; deposits refundable
        Settled // window closed and payouts locked in
    }

    struct Event {
        address organizer;
        address beaconKey; // venue display's ephemeral key; signs the beacon codes
        uint96 deposit; // per-attendee stake, in wei
        uint32 capacity; // max registrations
        uint32 minQuorum; // registrations required for the event to run at all
        uint8 k; // attestations required to be confirmed present
        uint64 registerDeadline;
        uint64 attestOpen;
        uint64 attestClose;
        Status status;
        uint32 registered;
        uint32 peerConfirmed; // confirmed via peer attestation alone
        uint32 orgConfirmed; // confirmed via the organizer fallback
        uint256 sharePerAttendee; // set at settle(): deposit + cut of the forfeited pool
    }

    /* ---------------------------------------------------------------------- */
    /*                                 Storage                                */
    /* ---------------------------------------------------------------------- */

    uint256 public nextEventId = 1;

    /// @dev Read via `getEvent`. Kept internal because a 14-field autogenerated getter blows
    ///      the stack limit without via-ir.
    mapping(uint256 => Event) internal _events;

    /// @dev eventId => attendee => registered
    mapping(uint256 => mapping(address => bool)) public isRegistered;
    /// @dev eventId => attendee => address recovered from their rotating codes
    mapping(uint256 => mapping(address => address)) public attestKeyOf;
    /// @dev eventId => attendee => attestations received
    mapping(uint256 => mapping(address => uint32)) public attestCount;
    /// @dev eventId => attendee => attestations they submitted themselves. Non-zero means they had
    ///      checked in, i.e. that they were in the room.
    mapping(uint256 => mapping(address => uint32)) public gaveCount;
    /// @dev eventId => attendee => block timestamp at which they proved they were at the venue.
    ///      Zero means not checked in. Stored rather than a bool because the public record is
    ///      more use if it says when somebody arrived, and it costs the same slot either way.
    mapping(uint256 => mapping(address => uint64)) public checkedInAt;
    /// @dev eventId => attendee => confirmed present
    mapping(uint256 => mapping(address => bool)) public isConfirmed;
    /// @dev eventId => attendee => payout already withdrawn
    mapping(uint256 => mapping(address => bool)) public hasClaimed;
    /// @dev eventId => keccak(low, high) => that unordered pair has already attested once
    mapping(uint256 => mapping(bytes32 => bool)) public pairUsed;

    /// @notice Attendee rotating codes change this often.
    uint256 public constant EPOCH = 15;

    /// @notice How many epochs of attendee code a submission may carry: the current one and the
    ///         three before it, so a code is worth something for 45 to 60 seconds after it appears.
    ///
    /// @dev Rotation and acceptance are separate numbers, and conflating them cost a working scan.
    ///      Acceptance used to be two epochs, which is 15 to 30 seconds — fine for the passkey
    ///      path, where an end-to-end vouch measures about a second, and a race for anyone on a
    ///      wallet, who has to read a confirmation dialog and press a button in the middle of it.
    ///      Worse, the simulation passes before that dialog and the real transaction reverts after
    ///      it, so the failure arrives having already been paid for.
    ///
    ///      Widening acceptance is close to free here. A forwarded code only ever helps somebody
    ///      vouch *for* an absent friend, and being vouched for is not what makes an account
    ///      present: that requires having vouched for somebody yourself, which requires having
    ///      checked in against a live venue beacon. The screen still changes every fifteen seconds,
    ///      so a screenshot still ages out — it just no longer ages out mid-transaction.
    uint256 public constant CODE_EPOCHS = 4;

    /// @notice Venue beacon codes rotate on this cadence, and a code is accepted for its own epoch
    ///         or the next — so 30 to 60 seconds separate reading the display from the check-in
    ///         landing on chain. That is slack for a wallet confirmation tap, and nothing more.
    ///
    /// @dev This used to be 120, because the beacon had to survive long enough for an attendee to
    ///      also find somebody and scan them. Now it only has to survive one transaction, so it
    ///      can be short — and short is what makes forwarding the venue code to somebody who is
    ///      not in the building expensive, since the accomplice has to be relaying it live.
    uint256 public constant BEACON_EPOCH = 30;

    /// @notice Grace period after the attestation window during which the organizer fallback may
    ///         still run. Settlement is blocked until it elapses, but only for rooms that
    ///         actually need the fallback — otherwise anyone could settle the instant the window
    ///         shut and strand the few people who did show up.
    uint256 public constant FALLBACK_WINDOW = 1 hours;

    /* ---------------------------------------------------------------------- */
    /*                                 Events                                 */
    /* ---------------------------------------------------------------------- */

    event EventCreated(
        uint256 indexed eventId,
        address indexed organizer,
        uint96 deposit,
        uint32 capacity,
        uint32 minQuorum,
        uint8 k,
        uint64 registerDeadline,
        uint64 attestOpen,
        uint64 attestClose
    );
    event BeaconKeySet(uint256 indexed eventId, address beaconKey);
    event Registered(uint256 indexed eventId, address indexed attendee, address attestKey);
    event CheckedIn(uint256 indexed eventId, address indexed attendee, uint64 beaconEpoch);
    event Attested(uint256 indexed eventId, address indexed attester, address indexed subject, uint64 epoch);
    event Confirmed(uint256 indexed eventId, address indexed attendee, bool viaOrganizer);
    event EventCancelled(uint256 indexed eventId, uint32 registered, uint32 minQuorum);
    event Settled(uint256 indexed eventId, uint32 confirmed, uint32 noShows, uint256 sharePerAttendee);
    event Claimed(uint256 indexed eventId, address indexed attendee, uint256 amount);

    /* ---------------------------------------------------------------------- */
    /*                                 Errors                                 */
    /* ---------------------------------------------------------------------- */

    error BadParams();
    error NoSuchEvent();
    error WrongStatus();
    error DeadlinePassed();
    error AtCapacity();
    error AlreadyRegistered();
    error NotRegistered();
    error WindowClosed();
    error WindowOpen();
    error SelfAttestation();
    error PairAlreadyUsed();
    error StaleCode();
    error BadCode();
    error StaleBeacon();
    error BadBeacon();
    error NotCheckedIn();
    error AlreadyCheckedIn();
    error NotOrganizer();
    error FallbackLocked();
    error FallbackPending();
    error QuorumMet();
    error QuorumNotMet();
    error NothingToClaim();
    error AlreadyClaimed();
    error TransferFailed();

    /* ---------------------------------------------------------------------- */
    /*                              Event setup                               */
    /* ---------------------------------------------------------------------- */

    /// @notice Create an event. The organizer sends no funds and can never withdraw any.
    /// @param beaconKey Address of the key held by the venue display.
    function createEvent(
        address beaconKey,
        uint96 deposit,
        uint32 capacity,
        uint32 minQuorum,
        uint8 k,
        uint64 registerDeadline,
        uint64 attestOpen,
        uint64 attestClose
    ) external returns (uint256 eventId) {
        if (deposit == 0 || capacity == 0 || k == 0) revert BadParams();
        if (beaconKey == address(0)) revert BadParams();
        if (minQuorum == 0 || minQuorum > capacity) revert BadParams();
        // A room needs at least k+1 people for peers to reach quorum without the fallback.
        if (minQuorum <= k) revert BadParams();
        if (registerDeadline <= block.timestamp) revert BadParams();
        if (attestClose <= attestOpen) revert BadParams();
        // Registration may run into the check-in window, so an organizer can take walk-ins — the
        // people a room actually attracts are the ones most worth keeping. Nothing downstream
        // depends on the two being sequential: attest() only asks that both parties are
        // registered, and settle() reads the final counts.
        //
        // What is refused is registration outliving check-in. Somebody who joins after the window
        // has shut can never be vouched for, so their deposit is forfeit the moment they pay it,
        // and no organizer should be able to configure that.
        if (registerDeadline > attestClose) revert BadParams();

        eventId = nextEventId++;
        Event storage e = _events[eventId];
        e.organizer = msg.sender;
        e.beaconKey = beaconKey;
        e.deposit = deposit;
        e.capacity = capacity;
        e.minQuorum = minQuorum;
        e.k = k;
        e.registerDeadline = registerDeadline;
        e.attestOpen = attestOpen;
        e.attestClose = attestClose;
        e.status = Status.Open;

        emit EventCreated(
            eventId, msg.sender, deposit, capacity, minQuorum, k, registerDeadline, attestOpen, attestClose
        );
        emit BeaconKeySet(eventId, beaconKey);
    }

    /// @notice Replace the venue beacon key before the window opens, in case the organizer loses
    ///         the device or has to swap venues. Locked once attestation starts so it cannot be
    ///         used to invalidate attestations already in flight.
    function setBeaconKey(uint256 eventId, address beaconKey) external {
        Event storage e = _load(eventId);
        if (msg.sender != e.organizer) revert NotOrganizer();
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp >= e.attestOpen) revert WindowClosed();
        if (beaconKey == address(0)) revert BadParams();

        e.beaconKey = beaconKey;
        emit BeaconKeySet(eventId, beaconKey);
    }

    /// @notice Stake the deposit and register. `attestKey` is the address of the key derived from
    ///         the caller's passkey PRF output; it signs their rotating codes.
    function register(uint256 eventId, address attestKey) external payable {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp >= e.registerDeadline) revert DeadlinePassed();
        if (e.registered >= e.capacity) revert AtCapacity();
        if (isRegistered[eventId][msg.sender]) revert AlreadyRegistered();
        if (attestKey == address(0)) revert BadParams();
        if (msg.value != e.deposit) revert BadParams();

        isRegistered[eventId][msg.sender] = true;
        attestKeyOf[eventId][msg.sender] = attestKey;
        e.registered += 1;

        emit Registered(eventId, msg.sender, attestKey);
    }

    /* ---------------------------------------------------------------------- */
    /*                              Attestation                               */
    /* ---------------------------------------------------------------------- */

    /// @notice Prove you are at the venue, by submitting a live signature from the venue beacon.
    ///         Required once per event before you can attest to anybody.
    /// @param beaconSig ECDSA signature by the venue beacon key over `beaconDigest(...)`.
    ///
    /// @dev The security of the whole scheme rests on this one transaction rather than on every
    ///      attestation, and it rests there because the chain — not the submitter — decides when
    ///      it happened. A beacon signature carries no timestamp of its own capture, so there is
    ///      no way to accept a stored one and still know when it was read; the only honest way to
    ///      date a beacon read is to make the read itself a transaction.
    function checkIn(uint256 eventId, uint64 beaconEpoch, bytes calldata beaconSig) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp < e.attestOpen) revert WindowOpen();
        if (block.timestamp >= e.attestClose) revert WindowClosed();
        if (!isRegistered[eventId][msg.sender]) revert NotRegistered();
        if (checkedInAt[eventId][msg.sender] != 0) revert AlreadyCheckedIn();

        uint64 nowBeacon = uint64(block.timestamp / BEACON_EPOCH);
        if (beaconEpoch != nowBeacon && beaconEpoch + 1 != nowBeacon) revert StaleBeacon();
        if (_recoverSig(beaconDigest(eventId, beaconEpoch), beaconSig) != e.beaconKey) revert BadBeacon();

        checkedInAt[eventId][msg.sender] = uint64(block.timestamp);
        emit CheckedIn(eventId, msg.sender, beaconEpoch);
    }

    /// @notice Attest that `subject` is physically present, by submitting a rotating code they
    ///         displayed. Credits both parties. Requires the caller to have checked in.
    /// @param code ECDSA signature by the subject's attest key over `codeDigest(...)`.
    function attest(uint256 eventId, address subject, uint64 epoch, bytes calldata code) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp < e.attestOpen) revert WindowOpen();
        if (block.timestamp >= e.attestClose) revert WindowClosed();
        if (subject == msg.sender) revert SelfAttestation();
        if (!isRegistered[eventId][msg.sender]) revert NotRegistered();
        if (!isRegistered[eventId][subject]) revert NotRegistered();

        // Arrival was proved once, on its own transaction. Nothing here re-checks the venue: the
        // subject's code is what binds this attestation to a person, and it is short-lived enough
        // that it cannot be a screenshot passed around.
        if (checkedInAt[eventId][msg.sender] == 0) revert NotCheckedIn();

        // The subject's code must be recent, so a screenshot taken a minute ago is useless — and a
        // code read a moment ago is still good when the transaction lands, however long its sender
        // spent looking at a wallet dialog.
        uint64 nowEpoch = uint64(block.timestamp / EPOCH);
        if (epoch > nowEpoch || nowEpoch - epoch >= CODE_EPOCHS) revert StaleCode();
        if (_recoverSig(codeDigest(eventId, subject, epoch), code) != attestKeyOf[eventId][subject]) {
            revert BadCode();
        }

        bytes32 pair = _pairKey(msg.sender, subject);
        if (pairUsed[eventId][pair]) revert PairAlreadyUsed();
        pairUsed[eventId][pair] = true;

        emit Attested(eventId, msg.sender, subject, epoch);

        attestCount[eventId][subject] += 1;
        attestCount[eventId][msg.sender] += 1;
        gaveCount[eventId][msg.sender] += 1;

        _maybeConfirm(eventId, e, subject);
        _maybeConfirm(eventId, e, msg.sender);
    }

    /// @dev Presence requires both being vouched for `k` times AND having vouched for someone
    ///      else at least once — and vouching requires having checked in, so the second condition
    ///      is what ties a confirmed attendee to the room.
    function _maybeConfirm(uint256 eventId, Event storage e, address who) private {
        if (isConfirmed[eventId][who]) return;
        if (attestCount[eventId][who] < e.k) return;
        if (gaveCount[eventId][who] == 0) return;

        isConfirmed[eventId][who] = true;
        e.peerConfirmed += 1;
        emit Confirmed(eventId, who, false);
    }

    /// @notice Fallback check-in by the organizer. Only unlocks after the window closes and only
    ///         when peers failed to establish quorum, i.e. fewer than k+1 attendees were
    ///         confirmed on their own. In a healthy room this reverts, so the organizer is
    ///         structurally unable to influence a normal settlement.
    /// @dev The organizer still cannot receive funds in any branch; the worst they can do here is
    ///      misattribute presence among addresses that already staked a deposit.
    function organizerCheckIn(uint256 eventId, address[] calldata attendees) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (msg.sender != e.organizer) revert NotOrganizer();
        if (block.timestamp < e.attestClose) revert WindowOpen();
        if (e.peerConfirmed > e.k) revert FallbackLocked();

        for (uint256 i; i < attendees.length; ++i) {
            address a = attendees[i];
            if (!isRegistered[eventId][a]) revert NotRegistered();
            if (isConfirmed[eventId][a]) continue;
            isConfirmed[eventId][a] = true;
            e.orgConfirmed += 1;
            emit Confirmed(eventId, a, true);
        }
    }

    /* ---------------------------------------------------------------------- */
    /*                               Settlement                               */
    /* ---------------------------------------------------------------------- */

    /// @notice Cancel an event whose registrations never reached `minQuorum`. Callable by anyone
    ///         once the registration deadline passes; every deposit becomes refundable.
    function cancelForQuorum(uint256 eventId) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp < e.registerDeadline) revert DeadlinePassed();
        if (e.registered >= e.minQuorum) revert QuorumMet();

        e.status = Status.Cancelled;
        emit EventCancelled(eventId, e.registered, e.minQuorum);
    }

    /// @notice Close out an event and lock in payouts. Callable by anyone once the attestation
    ///         window has passed — in production this is driven by a scheduled job, so no human
    ///         action is required and no human can withhold it.
    function settle(uint256 eventId) external {
        Event storage e = _load(eventId);
        if (e.status != Status.Open) revert WrongStatus();
        if (block.timestamp < e.attestClose) revert WindowOpen();
        if (e.registered < e.minQuorum) revert QuorumNotMet();
        // Rooms where peers reached quorum can never use the fallback, so they settle at once.
        // Everyone else waits out the grace period, or a griefer could settle at attestClose+1
        // and permanently deny the organizer the chance to check in the handful who came.
        if (e.peerConfirmed <= e.k && block.timestamp < e.attestClose + FALLBACK_WINDOW) {
            revert FallbackPending();
        }

        uint32 confirmed = e.peerConfirmed + e.orgConfirmed;
        uint32 noShows = e.registered - confirmed;

        if (confirmed == 0) {
            // Nobody could be confirmed present. Refund every deposit rather than issue an
            // unreliable verdict; the organizer captures nothing.
            e.status = Status.Cancelled;
            emit EventCancelled(eventId, e.registered, e.minQuorum);
            return;
        }

        uint256 forfeited = uint256(e.deposit) * noShows;
        e.sharePerAttendee = uint256(e.deposit) + forfeited / confirmed;
        e.status = Status.Settled;

        emit Settled(eventId, confirmed, noShows, e.sharePerAttendee);
    }

    /// @notice Withdraw whatever the caller is owed. Pull payment, so one failing recipient
    ///         cannot block anyone else.
    function claim(uint256 eventId) external {
        Event storage e = _load(eventId);
        if (!isRegistered[eventId][msg.sender]) revert NotRegistered();
        if (hasClaimed[eventId][msg.sender]) revert AlreadyClaimed();

        uint256 amount;
        if (e.status == Status.Cancelled) {
            amount = e.deposit;
        } else if (e.status == Status.Settled) {
            if (!isConfirmed[eventId][msg.sender]) revert NothingToClaim();
            amount = e.sharePerAttendee;
        } else {
            revert WrongStatus();
        }

        hasClaimed[eventId][msg.sender] = true;
        emit Claimed(eventId, msg.sender, amount);

        (bool ok,) = msg.sender.call{value: amount}("");
        if (!ok) revert TransferFailed();
    }

    /* ---------------------------------------------------------------------- */
    /*                                 Views                                  */
    /* ---------------------------------------------------------------------- */

    function getEvent(uint256 eventId) external view returns (Event memory) {
        return _events[eventId];
    }

    function confirmedCount(uint256 eventId) external view returns (uint32) {
        Event storage e = _events[eventId];
        return e.peerConfirmed + e.orgConfirmed;
    }

    function statusOf(uint256 eventId) external view returns (Status) {
        return _events[eventId].status;
    }

    /// @notice Whether the organizer fallback is currently available for this event.
    function fallbackAvailable(uint256 eventId) external view returns (bool) {
        Event storage e = _events[eventId];
        return e.status == Status.Open && block.timestamp >= e.attestClose && e.peerConfirmed <= e.k;
    }

    /// @notice The message a subject's attest key must sign for the given epoch.
    function codeDigest(uint256 eventId, address subject, uint64 epoch) public view returns (bytes32) {
        return _ethSigned(keccak256(abi.encode(address(this), eventId, subject, epoch)));
    }

    /// @notice The message the venue beacon key must sign for the given beacon epoch.
    function beaconDigest(uint256 eventId, uint64 beaconEpoch) public view returns (bytes32) {
        return _ethSigned(keccak256(abi.encode(address(this), eventId, "beacon", beaconEpoch)));
    }

    function currentEpoch() external view returns (uint64) {
        return uint64(block.timestamp / EPOCH);
    }

    function currentBeaconEpoch() external view returns (uint64) {
        return uint64(block.timestamp / BEACON_EPOCH);
    }

    /* ---------------------------------------------------------------------- */
    /*                                Internals                               */
    /* ---------------------------------------------------------------------- */

    function _load(uint256 eventId) private view returns (Event storage e) {
        e = _events[eventId];
        if (e.organizer == address(0)) revert NoSuchEvent();
    }

    function _ethSigned(bytes32 inner) private pure returns (bytes32) {
        return keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", inner));
    }

    function _pairKey(address a, address b) private pure returns (bytes32) {
        return a < b ? keccak256(abi.encodePacked(a, b)) : keccak256(abi.encodePacked(b, a));
    }

    function _recoverSig(bytes32 digest, bytes calldata sig) private pure returns (address) {
        if (sig.length != 65) revert BadCode();
        bytes32 r = bytes32(sig[0:32]);
        bytes32 s = bytes32(sig[32:64]);
        uint8 v = uint8(sig[64]);
        if (v < 27) v += 27;
        // Reject the malleable upper half of the curve order.
        if (uint256(s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) revert BadCode();
        address signer = ecrecover(digest, v, r, s);
        if (signer == address(0)) revert BadCode();
        return signer;
    }
}
