/// English copy, and the schema every other language is checked against.
///
/// Flat dotted keys rather than nested objects, because the lookup is a single map read with no
/// path walking and no `?.` chain that can quietly resolve to undefined halfway down. The dot is
/// punctuation, not structure.
///
/// This file is the source of truth in the type sense too: `Dict` is derived from it, so adding a
/// key here turns every other dictionary into a compile error until it is translated. That is the
/// point — an untranslated string is a bug we want the build to find, not something a Chinese
/// reader finds in the room.
export const en = {
  "nav.home": "Home",
  "nav.events": "Events",
  "nav.verify": "Verify",
  "nav.organizer": "Organizer",
  "nav.createEvent": "Create event",
  "nav.myEvents": "My events",
  "nav.payouts": "Payouts",
  "nav.overview": "Overview",
  "nav.myPasses": "My passes",

  "nav.myProof": "My proof",
  "me.signedOutBody": "Your own attendance record: which events you joined, which ones the room confirmed you at, and what you have staked. All of it read from the contract — anyone with the same address computes the same answer.",
  "me.signInFirst": "Sign in first — this page has no idea who you are until then.",
  "me.eventsJoined": "Events joined",
  "me.turnout": "Turnout",
  "me.staked": "Staked in total",
  "me.tabSettings": "Settings",
  "me.tabOverview": "Overview",
  "me.tabJoined": "Joined",
  "me.tabHosted": "Hosted",
  "me.eventsHosted": "Events hosted",
  "me.recentJoined": "Events you joined",
  "me.myHosted": "Events you host",
  "me.noneHosted": "You have not hosted an event yet.",
  "me.nRegistered": "{n} registered",
  "me.vsLastMonth": "{delta} on last month",
  "me.approxUsd": "≈ {amount} USD",
  "profile.title": "Your profile",
  "profile.edit": "Edit profile",
  "profile.intro": "Written to a contract that holds no money. Anyone can read it; only you can change yours. All of it optional — an empty profile costs you nothing.",
  "profile.name": "Name",
  "profile.nameHint": "What people see you as in this product.",
  "profile.bio": "One line about you",
  "profile.bioHint": "What you do, who you want to meet.",
  "profile.city": "City",
  "profile.cityHint": "Written the way event venues are — “Singapore”.",
  "profile.handleHint": "The handle only, not the whole link.",
  "profile.website": "Website",
  "profile.websiteHint": "Full address, https://…",
  "profile.saving": "Saving…",
  "profile.saved": "Saved on chain.",
  "profile.noChanges": "No changes",
  "profile.costs": "About {amount} for this write",
  "profile.noDirectory": "The profile contract has not been deployed yet, so there is nowhere to save this. It works once it is.",
  "me.impact": "Your impact",
  "me.reach": "People across your events",
  "me.places": "Cities and regions",
  "me.escrowed": "Held by the contract",
  "me.verified": "Verified present",
  "me.awaiting": "Not confirmed",
  "me.noneYet": "You have not joined any event yet.",
  "me.findOne": "See what's on",
  "me.unreachable": "Cannot reach the contract — the record below may be incomplete.",
  "common.back": "Back",
  "common.cancel": "Cancel",
  "common.loading": "Loading…",
  "common.view": "View",
  "common.join": "Join",
  "common.close": "Close",
  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.tapToCopy": "tap to copy",

  // A language's own name is never translated — somebody who cannot read the current UI has to be
  // able to find their way out of it. So these two values are identical in every dictionary.
  "lang.label": "Language",
  "lang.en": "English",
  "lang.zh": "中文",

  "events.title": "Discover events that really happen",
  "events.subtitle": "Join events worth turning up to, and leave a proof of attendance anyone can check.",
  "events.openNow": "Open now",
  "events.upcoming": "Upcoming",
  "events.thisWeek": "This week",
  "events.allCategories": "All",
  "events.myRegistrations": "My registrations",
  "events.registered": "registered",
  "events.featured": "Featured events",
  "events.seeAll": "See all",
  "events.search": "Search events",

  "organizer.title": "Organizer",
  "organizer.subtitle": "Your events, their live state, and nothing you can secretly override.",
  "organizer.greeting.morning": "Good morning, {who} 👋",
  "organizer.greeting.afternoon": "Good afternoon, {who} 👋",
  "organizer.greeting.evening": "Good evening, {who} 👋",
  "organizer.bannerTitle": "Build a community out of events that really happen",
  "organizer.bannerBody": "Host one, and let the people in the room prove each other were there. The contract holds the deposits; you never touch them.",
  "organizer.seeAllEvents": "See all events",
  "me.filterAllN": "All ({n})",
  "organizer.chipLive": "Live ({n})",
  "organizer.chipUpcoming": "Upcoming ({n})",
  "organizer.chipDone": "Finished ({n})",
  "organizer.manage": "Manage",
  "organizer.yourEvents": "Your events",
  "organizer.registered": "Registered",
  "organizer.heldInEscrow": "Held in escrow",
  "organizer.notInYourWallet": "not in your wallet",
  "organizer.confirmedPresent": "Confirmed present",
  "organizer.peerVerified": "peer verified",
  "organizer.liveNow": "{n} live now",
  "organizer.acrossAllEvents": "across all events",
  "organizer.livePulse": "Live pulse",
  "organizer.pulseNoPick": "Pick an event on the left and its vouching rhythm is drawn here.",
  "organizer.pulseCaption": "Vouches are arriving live from the room.",
  "organizer.payoutsAutomatic": "Payouts are automatic.",
  "organizer.payoutsBody":
    "You cannot release money or withhold it. The contract settles from the final proof graph.",
  "organizer.status": "Status",
  "organizer.people": "People",
  "organizer.event": "Event",
  "organizer.checkingIn": "Checking in",
  "organizer.upcoming": "Upcoming",
  "organizer.settled": "Settled",
  "organizer.record": "Record",

  "floor.checkIn": "Check in at the door",
  "floor.checkInHint":
    "Point your camera at the screen at the venue. Once, when you arrive — after that you can take all evening to meet people.",
  "floor.scanSomeone": "Scan someone",
  "floor.checkedIn": "Checked in",
  "floor.vouchedForYou": "vouched for you",
  "floor.doorsOpenIn": "Doors open in",
  "floor.codeGenerating": "generating…",
  "floor.refreshesIn": "refreshes in {n}s",
  "floor.scanVenueFirst": "Scan the venue display first — you only have to do it once.",
  "floor.codeAlt": "Your attendance code",
  "floor.pointAtCode": "Point at someone's code",
  "floor.pointAtDoor": "Point at the screen at the door",

  "venue.title": "Scan once to check in.",
  "venue.subtitle":
    "Do this when you walk in. After that the code up here stops mattering — go and meet people, and scan them whenever you get round to it.",
  "venue.refreshesIn": "Refreshes in",

  "event.deposit": "Entry deposit",
  "event.heldBy": "Held by the contract.",
  "event.notByOrganizer": "Not by the organizer.",
  "event.joinFor": "Join for {amount}",
  "event.aboutThis": "About this event",
  "event.details": "Event details",
  "event.peopleGoing": "{n} people are going",
  "event.onchainAttendance": "On-chain attendance",

  "verify.title": "Public record",
  "floor.title": "Attendance floor",
  "floor.notRegistered": "You're not registered for this event",
  "floor.notRegisteredBody": "A deposit is what makes an attestation worth anything, so the floor is only open to people who staked one.",
  "floor.goRegister": "Go back and register",
  "floor.doorsOpenBody": "Until then your code above is live and so is everyone else's — there is just nothing to submit yet. Keep this page open; it unlocks on its own.",
  "floor.countsPresent": "You count as present.",
  "floor.scanAtLeastOne": "Scan at least one person — being vouched for isn't enough on its own.",
  "floor.needMore": "{n} more",
  "floor.confirmedPresent": "confirmed present",
  "floor.room": "room",
  "floor.howProve": "How does this prove I'm here?",
  "floor.howProveBody": "Checking in spent a code from the screen at the door, in a transaction the chain timestamped — that is what puts you in the room. Each person you scan is another transaction crediting you both. Nobody reviews any of it.",
  "floor.vouchedByYou": "vouched by you",
  "floor.staleRead": "Can't reach the contract — the figures below may be out of date.",
  "floor.localChain": "Local chain — latency here is this node's block time, not Monad's.",
  "events.closesIn": "Closes in {t}",
  "events.endsIn": "Ends in {t}",
  "events.finished": "Finished",
  "events.cancelled": "Cancelled",
  "events.settled": "Settled",
  "events.vouchesNeeded": "{k} vouches to count as present",
  "events.sample": "Sample",
  "events.sampleDetail": "This is a sample event. Every figure below is a literal; no such event exists on any chain. It is here so the screen can be looked at.",
  "events.sampleNote": "Examples of how events will appear. No event has been opened on this contract yet.",
  "events.createFirst": "Create the first event",
  "events.noMatchTitle": "Nothing here yet",
  "events.noMatchBody": "No event matches that filter right now.",
  "events.showAll": "Show everything",
  "events.signInForMine": "Sign in on any event to see the ones you have joined.",
  "events.sourceNote": "Titles come from a contract that holds no money. The deposits sit somewhere else entirely.",
  "common.localChain": "Local chain — real transactions, fake money.",
  "common.noContract": "No contract configured.",
  "common.signIn": "Sign in",
  "common.retry": "Try again",
  "event.registered": "registered",
  "event.vouchesNeededLbl": "vouches needed",
  "event.minimumToRun": "minimum to run",
  "event.confirmedPresentShort": "confirmed present",
  "event.spotsTaken": "spots taken",
  "event.walkInsOn": "Walk-ins on",
  "event.walkInsOff": "Walk-ins off",
  "event.joinUntilClose": "You can join until the room closes",
  "event.registrationClosesAtDoors": "Registration closes when the doors open",
  "event.doorsOpenIn": "Doors open in {time}",
  "event.checkInOpenNow": "Check-in is open now",
  "event.checkInClosed": "Check-in has closed",
  "event.today": "Today",
  "event.tomorrow": "Tomorrow",
  "event.yesterday": "Yesterday",
  "event.stakeAndRegister": "Stake {amount} and register",
  "event.staking": "Staking…",
  "event.full": "This event is full",
  "event.registrationClosed": "Registration has closed",
  "event.youreIn": "You're in. Your deposit is held by the contract, not by the organizer.",
  "event.goToFloor": "Go to the floor",
  "event.openMyCode": "Open my attendance code",
  "event.signedInAs": "signed in as {name}",
  "event.useDifferentAccount": "use a different account",
  "event.chooseSignIn": "Choose how to sign in when you join.",
  "event.noWalletPlugin": "No wallet plugin required.",
  "event.publicProof": "Public proof",
  "event.publicProofSub": "Every accepted vouch is a transaction you can inspect",
  "myEvents.noneHosted": "You haven't hosted anything yet",
  "myEvents.noneHostedBody": "Use the New Event tab. There is no approval step and no listing fee — the deposits go to the contract, and you never hold them.",
  "organizer.yourEventsEmpty": "You haven't created an event yet.",
  "organizer.noVouchesYet": "No vouches yet — the chart fills as people scan each other.",
  "organizer.readOnly": "This event was created by {who}. You're viewing it read-only.",
  "organizer.view": "View",
  "verify.subtitle": "Who vouched for whom, and where the money went. Nothing here comes from our database — it is rebuilt from the contract's own events.",
  "verify.graph": "the attestation graph",
  "verify.arithmetic": "settlement arithmetic",
  "verify.everyVouch": "every vouch · {n} transactions",
  "verify.readingChain": "reading chain events…",
  "verify.backToEvent": "back to the event",
  "venue.setupTitle": "Venue display",
  "venue.setupBody": "Paste the beacon key you were given when the event was created.",
  "venue.start": "Start the display",
  "venue.forgetKey": "forget this key",
  "venue.beacon": "beacon {address}",
  // Two keys, one per line, so each language breaks the phrase where its own words break.
  // Inside an SVG there is no wrapping to fall back on.
  "art.noJudge1": "no central",
  "art.noJudge2": "judge",
  "home.searchPlaceholder": "Search events, places or organizers…",
  "home.signIn": "Sign in",
  "home.joinTitle": "I'm going to something",
  "home.hostTitle": "I'm running something",
  "strip.custodyTitle": "No organizer custody",
  "strip.custodyBody": "Deposits are held by the contract",
  "strip.peerTitle": "Peer proof",
  "strip.peerBody": "People in the room vouch for each other",
  "strip.publicTitle": "Publicly checkable",
  "strip.publicBody": "Every record is on chain",
  "strip.fastTitle": "Fast",
  "strip.fastBody": "Confirmation usually lands in seconds",
  "nav.forOrganizers": "For organizers",
  "home.builtOn": "Built on Monad",
  "home.fastFair": "Fast. Fair. On-chain.",
  "home.headline1": "Real People.",
  "home.headline2": "Real Attendance.",
  "home.script": "No organizers to trust. Just peers.",
  "home.joinSub": "Find events near you",
  "home.hostSub": "Create an event",
  "stats.title": "Monad makes it real-time.",
  "stats.finality": "0.6s",
  "stats.finalityLabel": "finality on Monad",
  "stats.cost": "0.026 MON",
  "stats.costLabel": "per vouch, at today's gas price",
  "stats.onchain": "On-chain",
  "stats.onchainLabel": "check it yourself",
  "home.step4Title": "The contract settles itself",
  "home.step4Body": "Everyone confirmed present reclaims their deposit and splits what the no-shows forfeited. The organizer has no function that touches it.",
  "home.howTitle4": "From joining to proof, in four steps",
  "home.howLink": "How does this work?",
  "live.title": "Happening now",
  "live.events": "events",
  "live.present": "confirmed present",
  "live.pool": "in escrow",
  "home.featured": "Featured events",
  "home.viewAll": "View all",
  "home.noneYet": "No events on this contract yet.",
  "home.noneYetBody": "Anyone can open one — there is no approval step, and the host never touches the deposits.",
  "footer.tagline": "Attendance you don't have to trust for.",
  "footer.source": "Source",
  "footer.contract": "Contract",
  "home.howItWorks": "How it works",

  "common.save": "Save",
  "common.gotIt": "Got it",
  "common.viewTx": "View transaction ↗",
  // The fallback name for an event nobody wrote a title for. A number, but a named number.
  "common.eventNumber": "Event #{id}",

  // The sign-in wall. First thing anybody meets, so every word of it is here — including the
  // lowercase micro-copy under the button, which is where somebody checks they are the right person.
  "identity.checking": "Checking this device…",
  "identity.noPrf": "This device can't hold a passkey key.",
  "identity.noPrfEmail": "Sign in with your email instead — nothing to install.",
  "identity.noPrfWallet": "You can take part with a browser wallet instead.",
  "identity.noPrfNeither": "Open this on a phone, or install a browser wallet.",
  "identity.continueEmail": "Continue with email",
  "identity.useBrowserWallet": "Use a browser wallet",
  "identity.continueWallet": "Continue with my wallet",
  "identity.why": "why?",
  "identity.whyBody1":
    "Your passkey provider doesn't support the WebAuthn PRF extension, which is what lets this app sign attendance codes without asking for your fingerprint every fifteen seconds. Chrome's built-in desktop passkeys are the usual culprit; iPhone with iCloud Keychain and Android with Google Password Manager both work.",
  "identity.whyBody2":
    "The wallet path derives the same kind of key from one signature — but then asks you to confirm every attestation, which is exactly the friction the passkey path removes.",
  "identity.setUpTitle": "Set up your attendance key",
  "identity.setUpBody":
    "One prompt, once. After that the app signs your codes silently — no fingerprint every fifteen seconds, no seed phrase, nothing to install.",
  "identity.createKey": "Create my key",
  "identity.haveOne": "I already have one",
  "identity.useWallet": "Use a wallet",
  "identity.useEmail": "Use email",
  "identity.boundTo": "bound to",
  // Lowercase on purpose: it is a footnote under the content, not a heading.
  "identity.signedInAs": "signed in as",
  "identity.wallet": "wallet",

  // Nothing in the wallet. The one screen where somebody is stuck and needs a way out.
  "funding.addMon": "Add MON to {what}",
  "funding.whatRegister": "register",
  "funding.short":
    "You have {have} and need about {need} — {short} short. The deposit is your own money going into the contract, so it cannot be covered for you; that is the part that makes a no-show cost something.",
  "funding.sendTitle": "Send MON to your address",
  "funding.sendBody":
    "Scan this from another wallet, or copy the address. Anything that can send on {chain} will do — an exchange withdrawal, a friend, your own other wallet.",
  "funding.qrAlt": "Your address as a QR code",
  "funding.topUp": "Top up",
  "funding.topUpWalletNote":
    "Card top-up runs through the account you signed in with, and is offered on the email path. With a browser wallet, buy MON wherever you normally would and send it to the address above.",
  // Wraps a <code>cast send</code>, so it is two halves of one sentence.
  "funding.localFund": "Local chain — fund this address with",
  "funding.localFundEnd": ".",

  "topup.cta": "Top up with a card",
  "topup.opening": "Opening…",
  "topup.submitted": "Submitted. Funds can take a few minutes to arrive — this page updates on its own.",
  "topup.done": "Topped up. Your balance updates here shortly.",
  "topup.closed": "Closed without topping up.",
  "topup.soonTitle": "Card top-up is coming",
  "topup.soonBody1":
    "This is where paying by card will go. It is not switched on yet, and the reason is not on our side: no provider sells MON into a wallet today. MoonPay has built it on Monad and has it suspended; Stripe does not list Monad as a destination.",
  "topup.soonBody2":
    "Until one of them does, use the address above — from an exchange, another wallet, or someone sending it to you. That works right now.",

  // What a failed scan says, standing in a room. These matter more than most of the UI, because
  // they are read once, quickly, by somebody who needs to know what to do next.
  //
  // `shortenError` is a plain function and cannot call a hook, so it carries the English literal
  // alongside the key and looks the key up only when a caller hands it `t`. Two contract errors
  // deliberately reuse the event screen's own wording rather than adding a second phrasing.
  "error.walletRejected": "You rejected this in your wallet.",
  "error.walletUnauthorised": "Your wallet has not authorised this site. Reconnect and try again.",
  "error.walletNoNetwork": "Your wallet does not have this network configured.",
  "error.walletBusy": "Your wallet already has a request open — check it for a pending prompt.",
  "error.insufficientFunds": "Not enough MON in this wallet to cover the gas for this transaction.",
  "error.noReason": "The wallet refused this without saying why.",
  "error.staleBeacon":
    "That venue code had already changed by the time check-in reached the chain. Scan the screen at the door again.",
  "error.badBeacon": "That venue code is for a different event.",
  "error.notCheckedIn": "Check in at the door first — scan the screen at the venue. You only do it once.",
  "error.alreadyCheckedIn": "You are already checked in. Go and scan people.",
  "error.staleCode": "Their code expired before it reached the chain. Ask them to hold it steady and scan again.",
  "error.badCode": "That code didn't verify. It may belong to a different event.",
  "error.pairAlreadyUsed": "You two have already vouched for each other. One scan counts for both of you.",
  "error.selfAttestation": "That's your own code — you need somebody else's.",
  "error.notRegistered": "One of you hasn't registered for this event.",
  "error.windowOpen": "Check-in hasn't opened yet.",
  "error.windowClosed": "Check-in has closed for this event.",
  "error.wrongStatus": "This event is no longer open.",
  "error.alreadyRegistered": "You're already registered.",
  "error.quorumNotMet": "Too few people registered for this event to run.",
  "error.fallbackPending": "Settlement is waiting out the fallback window.",

  "vouch.landedIn": "Landed in",
  "vouch.you": "You",

  "registered.inContract": "{amount} is now in the contract",
  "registered.body":
    "Not in the organizer's wallet. Your deposit comes back when the room proves you were there — along with a share of what the no-shows leave behind.",
  "registered.next": "Next:",
  "registered.opensIn": "check-in opens in {t}",
  "registered.openNow": "check-in is open now",
  "registered.andNeedOne": ", and you need 1 person to vouch for you.",
  "registered.andNeed": ", and you need {n} people to vouch for you.",
  "registered.viewTx": "View registration transaction ↗",

  "payout.paidOut": "Paid out",
  // Split so the surplus can carry its own colour. The amount lands between the two.
  "payout.extraPre": "Your {amount} deposit back, plus",
  "payout.extraPost": "from the people who didn't show up.",
  "payout.noExtra":
    "Your {amount} deposit back. Everyone who registered turned up, so there was nothing forfeited to share.",
  "payout.noApproval":
    "Nobody approved this. The split was fixed when the window closed, by who vouched for whom.",
  "payout.seeTx": "see the transaction ↗",

  "handoff.title": "Set up the display at the door",
  "handoff.body":
    "Scan this from the device that will sit at the entrance — a spare phone, a tablet, a laptop. It opens the venue display with this key already loaded.",
  "handoff.qrAlt": "Venue display setup code",
  "handoff.sameDevice": "Already on the right device? Open it here instead — no scanning needed.",
  "handoff.keyWarning":
    "The code carries the key. Treat it like the key itself: it signs venue codes for this event and nothing else, and it stops meaning anything once check-in closes.",
  "venue.openDisplay": "Open the venue display",

  "listing.whatPeopleSee": "What people see in the listing",
  "listing.editHint":
    "Change this whenever you like. It is stored separately from the deposits and cannot affect them.",
  "listing.noTitleHint":
    "This event has no title yet, so it shows as a number on the events page. Adding one costs a small amount of gas and nothing else.",
  "listing.saved": "Saved. The events page will show it within a few seconds.",
  "listing.saving": "Saving…",
  "listing.settingUp": "Setting up descriptions…",
  "listing.title": "Title",
  "listing.titleHint": "e.g. Thursday reading group",
  "listing.noTitleWarn": "You can create it without a title — it will just be listed as a number.",
  "listing.description": "Description",
  "listing.blurbPlaceholder": "Who it's for, what happens, where.",
  "listing.venue": "Where",
  "listing.venueHint": "Somewhere findable — Kaiyuan Space Singapore, or just Online.",
  "listing.tags": "Tags (optional)",
  "listing.tagsHint": "Comma separated — reading group, in person, weekly. Searchable.",
  "listing.link": "Link (optional)",
  "listing.linkHint": "A fuller page, if you have one",
  "listing.addTitle": "Add a title",

  "event.runDevChain": "Run",
  "event.runDevChainEnd": ", then restart the dev server.",
  "event.cantReach": "Can't reach the contract right now — {why}",
  "event.signedInLabel": "Signed in as",
  "event.walletBalance": "wallet {address} · balance {balance}",
  "event.revertedOnChain": "Registration reverted on chain.",
  "event.joinUntilTime": "You can join until {time}",
  "event.howTitle": "How attendance works",
  "event.howSub": "Check in at the door once, then take your time",
  "event.howP1":
    "When you arrive, scan the screen at the door. Its code changes every thirty seconds and check-in spends it immediately, so the chain itself records when you walked in — that is the part somebody in another city cannot fake.",
  "event.howP2":
    "After that there is no clock on the venue at all. Meet people, talk, scan them whenever you get round to it. Their codes change every fifteen seconds, so a screenshot forwarded to somebody else is worthless two rotations later.",
  "event.howP3":
    "And being counted present requires having vouched for somebody yourself — which requires having checked in. Every account that settles as present came through the door. You cannot be relayed in by a friend.",
  "event.depositTitle": "What happens to the deposit",
  "event.depositSub": "Show up, and it comes back with more",
  "event.depositP1":
    "Show up and it returns to you, plus a share of the deposits left behind by people who did not",
  "event.surplusAbout": "— about",
  "event.surplusAtCount": "at the current count",
  "event.depositP1End": ".",
  "event.depositP2": "Don't, and your deposit goes to the people who did.",
  "event.depositP3":
    "If too few people register for the event to run, every deposit is refunded in full — including yours.",
  "event.signInSheetTitle": "How do you want to sign in?",
  "event.signInSheetSub": "One of these, once. Nothing to install.",
  "event.signedInPressAgain": "You're signed in — press register again.",

  "organizer.showing": "Showing",
  "organizer.awaitingSettlement": "Awaiting settlement",
  "organizer.nothingHostedBody":
    "Use Create event. There is no approval step and no listing fee — the deposits go to the contract, and you never hold them.",
  "organizer.pulsePast": "How the vouches arrived, oldest first.",
  "organizer.pulseAria": "{n} vouches, oldest to most recent: {bars}",
  "organizer.vouchOne": "1 vouch",
  "organizer.vouchMany": "{n} vouches",
  "organizer.overTheLast": " over the last {t}",
  "organizer.logsUnavailable": "Couldn't read the attestation logs just now.",
  "organizer.payoutsDetail":
    "There is no function on this contract that pays the organizer, and no parameter you can change after registration opens. When the window closes, anyone — or a scheduled job — can trigger the split, and the split is already determined.",
  "organizer.footNote":
    "Everything on this screen is read from the contract. The organizer role exists to describe an event, not to decide its outcome.",
  "organizer.loadingEvent": "Loading event…",
  "organizer.checkingInEndsIn": "Checking in · ends in {t}",
  "organizer.stillWalkIns": " · still taking walk-ins",
  "organizer.registeringUntil": "Registering until {time}",
  "organizer.waitingDoors": "Registration closed — waiting for the doors",
  "organizer.checkInClosed": "Check-in closed",
  "organizer.depositPer": "Deposit per attendee",
  "organizer.ofPlaces": "{n} of {cap} places",
  "organizer.vouchesEach": "{n} · {k} vouches each",
  "organizer.runsIfAtLeast": "Runs if at least",
  "organizer.nRegister": "{n} register",
  "organizer.statusOpen": "Open",
  "organizer.statusCancelled": "Cancelled — everyone refunded",
  "organizer.venueNote":
    "— the screen at the door, which remembers its key in that browser. Or read the",
  "organizer.venueNoteEnd": ".",
  "organizer.publicRecord": "public record",
  "organizer.fallbackTitle": "Fallback check-in is unlocked",
  "organizer.fallbackBody":
    "Peers couldn't establish quorum — too few people showed up to vouch for each other. You may confirm who was actually there. This is the only branch where your word counts for anything, and it still gives you no way to receive the money.",
  "organizer.fallbackHint":
    "Paste addresses to confirm, one per line. (In a healthy room this whole section is absent, because the contract refuses the call.)",
  "organizer.noValidAddresses": "No valid addresses.",
  "organizer.confirming": "Confirming…",
  "organizer.confirmAttendees": "Confirm these attendees",

  "create.subtitle": "One clear step at a time. Advanced details only when you need them.",
  "create.creating": "Creating…",
  "create.savingDescription": "Saving the description…",
  "create.reverted": "createEvent reverted",
  "create.descriptionFailed": "Event created, but the description didn't save: {why}",
  "create.createdTitle": "Event #{id} created",
  "create.beaconBody":
    "Save the venue beacon key below and load it on the device at the door. It signs the rotating venue code — without it, nobody can prove they were in the room.",
  "create.beaconWarning":
    "Shown once. It holds no funds, but losing it means the venue display can't sign — and the contract only lets the key be replaced before the doors open.",
  "create.descriptionFailedNote":
    "The event itself is fine — deposits, check-in and settlement do not depend on it. Add the words from the Overview tab whenever you like.",
  "create.backToEvents": "Back to your events",
  "create.stepAbout": "About",
  "create.stepRules": "Rules",
  "create.aboutTitle": "About the event",
  "create.aboutSub": "What people see in the listing.",
  "create.next": "Next · the rules →",
  "create.rulesTitle": "The rules",
  "create.rulesSub": "Fixed once registration opens — including for you.",
  "create.deposit": "Deposit (MON)",
  "create.capacity": "Capacity",
  "create.quorumHint": "must exceed vouches",
  "create.vouchesNeeded": "Vouches needed",
  "create.kHint": "3 is a good default",
  "create.doorsMins": "Doors open in (mins)",
  "create.doorsHint": "when check-in starts",
  "create.runsMins": "Runs for (mins)",
  "create.runsHint": "how long check-in stays open",
  "create.walkIns": "Take walk-ins",
  "create.walkInsOnBody":
    "People can still join after the doors open — the ones a room attracts on the night are often the ones worth keeping.",
  "create.walkInsOffBody":
    "Registration closes when the doors open. Classic RSVP: decide in advance, or not at all.",
  "create.noCustodyNote":
    "You send no funds and gain no spending power. Deposits go to the contract; the split is decided by who vouches for whom.",

  // The two dev panels keep their internals in English — addresses, gas figures, function names are
  // not copy. What a person could act on wrongly is translated.
  "deploy.escrowWarning":
    "Every event on the current escrow is left behind. Deposits there stay claimable at the old address, but nothing here will point at them again.",
  "deploy.dirTitle": "Set up once for this deployment",
  "deploy.dirBodyPre": "Events currently show as",
  "deploy.dirBodyPost":
    "rather than a name. Titles live in a second contract, so the one holding deposits never has to change to store text — deploy it once and every event after this can describe itself.",
  "deploy.dirDone":
    "Deployed. Nothing to configure — the address is derived from the bytecode, so every build finds it.",
  "deploy.dirTx": "deployment transaction",
  "deploy.dirBusy": "Deploying…",
  "deploy.dirCta": "Deploy the directory",
  "deploy.dirGas":
    "About 0.2 MON. The limit is estimated at the time of the press and padded by a fifth — a pinned number goes stale the moment the contract grows, and Monad charges the limit either way.",
  "home.redirecting": "Taking you to the event…",
  "home.howItWorksSub": "A deposit, a room, and a contract that settles from what the room proves about itself.",
  "home.step1Title": "Put a deposit down",
  "home.step1Body": "The deposit is what holds your place. The contract takes it — the organizer never does.",
  "home.step2Title": "Check in at the door",
  "home.step2Body": "Scan the screen at the venue once on arrival. That is its own transaction, so the chain timestamps when you walked in — not the submitter.",
  "home.step3Title": "Vouch for the people you meet",
  "home.step3Body": "Scan people you actually meet; one scan credits you both. Their code rotates every fifteen seconds, so a forwarded screenshot is worthless.",
  "home.custodyNote": "Whoever created the event has no function that releases, withholds, or receives a single wei. That is not a promise — it is the absence of a door.",
  "home.bothRoles": "The same account can do both — these are two ways in, not two kinds of person. Anyone can host; there is no approval step.",
  "home.readPublicRecord": "Read the public record",
  "venue.eyebrow": "Venue beacon",
  "venue.setupEyebrow": "One-time setup",
  "venue.setupHeadline": "Load the venue beacon",
  "venue.credentialNote": "The beacon key is a credential. It stays on this device and is removed from the address bar after setup.",
  "venue.keyHoldsNoFunds": "It holds no funds and can never move money — it only signs. Stored in this browser only; it is never sent anywhere.",
  "venue.notAKey": "That doesn't look like a private key (64 hex characters).",
  "venue.invalidKey": "That key isn't valid.",
  "verify.openOnExplorer": "Open on explorer",
  "verify.roomDecided": "The room decided this",
  "verify.eachLine": "Each line is a real accepted vouch.",
  "verify.settlement": "Settlement",
  "verify.settlementRow": "settlement",
  "verify.eachReceives": "each confirmed attendee receives",
  "verify.eachWouldReceive": "each confirmed attendee would receive",
  "verify.nobodyConfirmedYet": "Nobody has been confirmed present yet.",
  "verify.depositPlusShare": "{deposit} deposit + {share} share of no-shows",
  "verify.confirmedPresent": "{n} confirmed present",
  "verify.getDepositBack": "get their deposit back",
  "verify.neverConfirmed": "{n} never confirmed",
  "verify.forfeit": "forfeit {amount}",
  "verify.settledNote": "Fixed by the contract at settlement. The divisor cannot move afterwards, so the pool can never be over-committed.",
  "verify.settlementTx": "settlement transaction",
  "verify.projectedNote": "Not final. If nobody can be confirmed present, the contract refunds every deposit rather than issue an unreliable verdict — and the organizer receives nothing in that branch either.",
  "verify.noOrganizerApproved": "No organizer approved this.",
  "verify.payoutFollowsGraph": "The payout follows the graph at the close of the window.",
  "verify.blocks": "blocks {from}–{to}",
  "verify.viaEnvio": "Attestation graph indexed by Envio HyperIndex.",
  "verify.viaLogs": "Attestation graph read from contract logs directly — the index was unreachable.",
  "verify.noPayoutFunction": "There is no function on this contract that pays the organizer. Check the source: every branch of claim pays msg.sender, and only registered attendees can reach it.",
  "identity.creatingKey": "Creating your key…",
  "identity.unlocking": "Unlocking…",
  "identity.waitingWallet": "Waiting for your wallet…",
  "identity.signInFailedLoad": "Sign-in failed to load — {why}. This is the email sign-in code itself not arriving, usually an ad blocker or privacy extension blocking it, or a page left open across a redeploy. Reload the page first; if that does not help, allow this site in the extension.",
  "identity.signInBlocked": "Sign-in didn't load. Something on this browser may be blocking privy.io — an ad blocker, a privacy extension, or a strict tracking setting. Allow it for this site, or use a browser wallet.",
  "identity.openingSignIn": "Opening sign-in…",
  "identity.noWallet": "No browser wallet found.",
  "graph.confirmed": "confirmed present",
  "graph.neverConfirmed": "registered, never confirmed",
  "graph.numberMeans": "number = vouches received",
  "graph.present": "present",
  "graph.presentFallback": "present (organizer fallback)",
  "graph.forfeited": "forfeited",
  "graph.notYet": "not confirmed yet",
  "floor.alreadyCheckedIn": "You're already checked in — keep looking for a person's code.",
  "floor.checkedInFlash": "Checked in. Now go and scan people — no rush, this lasts all event.",
  "deploy.dirBody": "Events can only show a number until this is deployed — titles and descriptions live in a second contract, so the one holding deposits never has to change to store text. Whoever deploys it, everyone uses it: its address is derived from the escrow, not from the deployer. Once it is deployed this block stops appearing.",
  "event.noSuchTitle": "There is no event here yet",
  "event.noSuchBody": "This contract has no event with that number. Either it has not been created yet, or the link points at a different deployment. Nothing has been lost — there was never anything here to lose.",
  "home.closeTitle": "Don't take our word for any of it",
  "home.closeBody": "The contract is on Monad testnet and its source is verified. Every deposit, every vouch and every payout is a transaction you can read without asking us anything.",
  "gate.orgTitle": "What hosting an event does",
  "gate.orgBody": "You set the terms once, and then the contract runs them. There is no step where you decide who showed up.",
  "gate.org1Title": "You set the terms",
  "gate.org1Body": "Deposit, capacity, how many vouches count as present, and when the doors open. After registration starts, none of it can change — not by you, not by anyone.",
  "gate.org2Title": "People arrive and prove it",
  "gate.org2Body": "They check in against the screen at your door, then vouch for each other. You put the screen up; you do not mark anybody present.",
  "gate.org3Title": "The contract settles",
  "gate.org3Body": "Whoever was confirmed present takes their deposit back and splits what the no-shows left. You receive nothing, because there is no function that could pay you.",
  "gate.floorTitle": "What you'll do at the venue",
  "gate.floorBody": "Two scans and a wait. Everything else happens on chain without anybody's permission.",
  "gate.floor1Title": "Check in at the door",
  "gate.floor1Body": "Point your camera at the screen at the venue. Once, when you arrive — it lasts the whole event.",
  "gate.floor2Title": "Scan the people you meet",
  "gate.floor2Body": "One scan credits both of you. No rush — their code changes every fifteen seconds, and the next one is already on screen.",
  "gate.floor3Title": "Take your deposit back",
  "gate.floor3Body": "Once enough people have vouched for you, you count as present — and when the window closes you get your stake plus a share of what the no-shows left behind.",

  // The scan overlay and everything it can say when a scan does not work.
  //
  // These were English literals until the whole flow was read in Chinese: the camera screen and
  // every one of its failure messages. Which meant the one moment where somebody needs to be told
  // precisely what went wrong — standing in a room, holding a phone at somebody else's phone — was
  // the moment the app stopped speaking their language.
  "scan.hintPeer":
    "Hold the other phone close, so the code fills most of the picture. Codes change every 15 seconds — if one expires mid-scan, the next is already on screen.",
  "scan.hintVenue":
    "The venue display is showing a code that changes every 30 seconds. This is sent straight to the chain, so scan it where it is — not from a photograph.",
  "scan.cameraDenied": "Camera permission denied.",
  "scan.cameraFailed": "Could not start the camera.",

  "floor.notPeerProofCode": "Not a PeerProof code.",
  "floor.ownCode": "That's your own code — you need somebody else's.",
  "floor.codeFailedVerification": "That code failed verification.",
  "floor.venueCodeMalformed": "That venue code is malformed.",
  "floor.checkInOpensIn": "Code reads fine — check-in opens in {time}.",
  "floor.checkInClosed": "Code reads fine, but check-in has closed for this event.",
  "floor.checkInReverted": "Check-in reverted on chain. Scan the venue display again.",
  "floor.attestReverted": "That attestation reverted on chain.",
  "floor.settleEvent": "Settle this event",
  "floor.yourDepositBack": "Your deposit back",
  "floor.shareOfForfeited": "Share of forfeited deposits",

  "timeline.whatParticipants": "What participants will experience",
  "timeline.nowRegistration": "Now · registration",
  "timeline.doorsOpen": "Doors open",
  "timeline.inTime": "in {time}",
  "timeline.eventEnds": "Event ends",
  "timeline.afterTime": "after {time}",
  "timeline.walkInsNote":
    "The bar is filled for as long as people can still register — with walk-ins on, that is the whole event.",
  "timeline.noWalkInsNote":
    "Registration closes the moment the doors open. Nobody joins after that.",

  "bridge.settingUpKey": "Setting up your key…",

  "graph.nobodyRegistered": "Nobody has registered yet.",
  "graph.noVouchesYet": "No lines yet — one appears each time somebody scans somebody else.",
};

/// Every dictionary has exactly these keys. Widening the values to `string` is deliberate: the
/// English literals are copy, not a contract, and `t()` returns a plain string either way.
export type Dict = Record<keyof typeof en, string>;
