import type { Dict } from "@/lib/dict/en";

/// Simplified Chinese.
///
/// Typed as `Dict`, so a key added to English and forgotten here fails `tsc` rather than leaking an
/// English sentence into a Chinese page — which is the failure mode that actually happens, and the
/// one nobody notices until it is on screen in front of a room.
///
/// Written as product copy, not as a translation of product copy: same job, same brevity, said the
/// way a Chinese app would say it. The `{n}` / `{amount}` placeholders are part of the string and
/// must survive — but their position is free, and in several of these it moves.
export const zh: Dict = {
  "nav.home": "首页",
  "nav.events": "活动",
  "nav.verify": "验证",
  "nav.host": "主办",
  "nav.mine": "我的",
  "nav.organizer": "主办方",
  "nav.createEvent": "创建活动",
  "nav.myEvents": "我的活动",
  "nav.payouts": "结算",
  "nav.overview": "总览",
  "nav.myPasses": "我的门票",

  "nav.myProof": "我的证明",
  "me.signedOutBody": "这里是你自己的出席记录:报名过哪些活动、哪些被现场的人确认过、押金累计多少。全部从合约读,别人用同一个地址也能算出同样的结果。",
  "me.signInFirst": "先登录，这里才知道你是谁。",
  "me.eventsJoined": "报名过的活动",
  "me.turnout": "到场率",
  "me.staked": "累计押金",
  "me.tabSettings": "设置",
  "me.tabOverview": "概览",
  "me.tabJoined": "我参加的",
  "me.tabHosted": "我主办的",
  "me.tabRewards": "我的奖励",
  "me.tabIdentity": "我的身份",
  "me.eventsHosted": "主办的活动",
  "me.recentJoined": "最近参加的活动",
  "me.myHosted": "我主办的活动",
  "me.noneHosted": "你还没有办过活动。",
  "me.nRegistered": "{n} 人已报名",
  "me.vsLastMonth": "较上月 {delta}",
  "me.approxUsd": "≈ {amount} USD",
  "profile.title": "个人资料",
  "profile.edit": "编辑资料",
  "profile.intro": "这些会写进一个不持有任何资金的合约,谁都读得到,只有你能改自己的。全部可选——不填也不影响任何功能。",
  "profile.name": "昵称",
  "profile.nameHint": "别人在这个产品里看到的名字。",
  "profile.bio": "一句话介绍",
  "profile.bioHint": "你做什么、想认识谁。",
  "profile.city": "所在城市",
  "profile.cityHint": "和活动的地点用同一种写法,比如「新加坡」。",
  "profile.handleHint": "只填用户名,不用填整条链接。",
  "profile.website": "个人网站",
  "profile.websiteHint": "完整地址,比如 https://…",
  "profile.saving": "提交中…",
  "profile.saved": "已保存到链上。",
  "profile.noChanges": "没有改动",
  "profile.costs": "这一笔约 {amount}",
  "profile.noDirectory": "资料合约还没有部署,所以现在还存不了。部署之后这里就能用。",
  "me.impact": "我的影响力",
  "me.identityTags": "我的身份标签",
  "me.identityEmpty": "还没有。报过一次名、或者办过一场活动,这里就会有。",
  "me.identityNote": "从链上记录算出来的,不是自己填的。",
  "me.tagAttendee": "参与者",
  "me.tagOrganizer": "活动主办方",
  "me.tagRegular": "常客",
  "me.tagCommunity": "社区组织者",
  "me.tagPerfect": "全勤",
  "me.earned": "押在场上的",
  "me.achievements": "贡献与徽章",
  "me.badgeEarly": "早期参与者",
  "me.badgeEarlyHint": "报名过至少一场",
  "me.badgeActive": "活跃参与者",
  "me.badgeActiveHint": "被确认到场 3 次",
  "me.badgeOrganizer": "活动组织者",
  "me.badgeOrganizerHint": "办过至少一场",
  "me.badgeLeader": "社区领袖",
  "me.badgeLeaderHint": "办的活动累计 25 人报名",
  "me.badgeNote": "每一枚都是链上记录里的一个门槛,没有人在背后评定。",
  "me.badgeQuote": "最好的社区,是由真的到场的人建起来的。",
  "me.roles": "我的角色",
  "me.share": "分享主页",
  "me.joined": "{when} 加入",
  "me.viewingPublic": "你正在看 {who} 的公开主页。这一页上的每一项都能自己去链上核。",
  "me.noneYetPublic": "这个账号还没有报名过活动。",
  "me.noneHostedPublic": "这个账号还没有办过活动。",
  "me.shareCopy": "复制这个链接:",
  "me.roleAttendee": "参与者",
  "me.roleAttendeeBody": "去活动,留下可验证的到场证明。",
  "me.roleOrganizer": "活动主办方",
  "me.roleOrganizerBody": "办活动,让到场的人互相证明。",
  "me.roleJoined": "活动参与",
  "me.roleHosted": "活动主办",
  "me.rolesAria": "{role}这一栏的两个数字",
  "me.calendar": "活动足迹",
  "me.calPrev": "上个月",
  "me.calNext": "下个月",
  "me.calAttended": "参加并被确认",
  "me.calHosted": "我主办的",
  "me.calEmpty": "这个月还没有记录。",
  "me.reach": "总参与者(我主办的活动)",
  "me.places": "城市 / 地区",
  "me.escrowed": "合约托管押金总额",
  "me.verified": "已验证到场",
  "me.awaiting": "还没确认",
  "me.noneYet": "你还没有报名过任何活动。",
  "me.findOne": "去看看有什么活动",
  "me.unreachable": "读不到合约,下面的记录可能不全。",
  "common.back": "返回",
  "common.cancel": "取消",
  "common.loading": "加载中…",
  "common.view": "查看",
  "common.join": "参加",
  "common.close": "关闭",
  "common.copy": "复制",
  "common.copied": "已复制",
  "common.tapToCopy": "点一下复制",

  // Not translated on purpose — see en.ts. Somebody stuck in the wrong language has to be able to
  // read their way out.
  "lang.label": "语言",
  "lang.en": "English",
  "lang.zh": "中文",

  "events.title": "探索真实发生的社区活动",
  "events.subtitle": "加入有价值的线下与线上活动，留下可验证的参与证明。",
  "events.openNow": "正在进行",
  "events.upcoming": "即将开始",
  "events.thisWeek": "本周",
  "events.allCategories": "全部",
  "events.myRegistrations": "我的报名",
  // Sits after a count: 「12 人已报名」.
  "events.registered": "人已报名",
  "events.confirmedCount": "已验证参与者",
  "events.joinNow": "立即报名",
  "events.featured": "精选活动",
  "events.seeAll": "查看全部",
  "events.search": "搜索活动、城市或主办方…",

  "organizer.title": "主办方",
  "organizer.subtitle": "你的活动和它们的实时状态——没有一项是你能暗中改动的。",
  "organizer.greeting.morning": "{who}，早上好 👋",
  "organizer.greeting.afternoon": "{who}，下午好 👋",
  "organizer.greeting.evening": "{who}，晚上好 👋",
  "organizer.bannerTitle": "用真实的活动，建立可信的社区",
  "organizer.bannerGuest": "办活动的人看到的就是这一页 👋",
  "organizer.bannerBody": "办一场活动,让到场的人互相证明。押金由合约保管,你从头到尾碰不到。",
  "organizer.seeAllEvents": "看全部活动",
  "me.filterAllN": "全部 ({n})",
  "organizer.chipLive": "进行中 ({n})",
  "organizer.chipUpcoming": "未开始 ({n})",
  "organizer.chipDone": "已结束 ({n})",
  "organizer.manage": "管理活动",
  "organizer.manageSub": "这一场的数据,和可以随时改的内容。",
  "organizer.manageData": "数据",
  "organizer.manageEdit": "修改内容",
  "organizer.yourEvents": "你的活动",
  "organizer.registered": "已报名",
  "organizer.registeredShort": "已报名",
  "organizer.liveEvents": "进行中的活动",
  "organizer.management": "活动管理",
  "organizer.awaitingVouches": "待作证",
  "organizer.noShows": "未到场",
  "organizer.capacity": "名额",
  "organizer.ofNTotal": "共 {n} 场",
  "organizer.heldInEscrow": "合约托管中",
  "organizer.notInYourWallet": "不在你的钱包里",
  "organizer.confirmedPresent": "确认到场",
  "organizer.peerVerified": "同伴互证",
  "organizer.liveNow": "{n} 场正在进行",
  "organizer.acrossAllEvents": "所有活动合计",
  "organizer.livePulse": "实时动态",
  "organizer.analytics": "数据分析与结算",
  "organizer.trend": "参与人数趋势",
  "organizer.trendEmpty": "办过活动之后,这里会把每一场的报名和到场画成两条线。",
  "organizer.payoutState": "押金流向",
  "organizer.releasedOf": "已经退还,共 {total}",
  "organizer.stepSettled": "已结算 {n} 场",
  "organizer.stepReleased": "已退还 {amount}",
  "organizer.stepHeld": "合约还托管着 {amount}",
  "organizer.seriesConfirmed": "累计作证",
  "organizer.seriesRegistered": "累计报名",
  "organizer.pulseNoPick": "先在左边选一场活动，这里会画出它的作证节奏。",
  "organizer.pulseCaption": "现场的互证正在实时传来。",
  "organizer.payoutsAutomatic": "结算是自动的。",
  "organizer.payoutsBody": "你无法发钱，也无法扣钱。合约按最终的证明图自动结算。",
  "organizer.status": "状态",
  "organizer.people": "人数",
  "organizer.event": "活动",
  "organizer.checkingIn": "签到中",
  "organizer.upcoming": "即将开始",
  "organizer.settled": "已结算",
  "organizer.record": "记录",

  "floor.checkIn": "在门口签到",
  "floor.checkInHint": "进场时把摄像头对准现场的屏幕，扫一次就行。之后整晚都可以慢慢认识人。",
  "floor.scanSomeone": "扫描他人",
  "floor.checkedIn": "已签到",
  // Sits after a count: 「3 人为你作证」.
  "floor.vouchedForYou": "人为你作证",
  "floor.doorsOpenIn": "距开场还有",
  "floor.codeGenerating": "生成中…",
  "floor.refreshesIn": "{n} 秒后刷新",
  "floor.scanVenueFirst": "先扫门口的屏幕，只需要一次。",
  "floor.codeAlt": "你的到场码",
  "floor.pointAtCode": "对准对方的二维码",
  "floor.pointAtDoor": "对准门口的屏幕",

  "venue.title": "扫一次，完成签到。",
  "venue.subtitle":
    "进门时扫一下就好。之后这块屏幕就不重要了——去认识人，什么时候想扫他们都行。",
  "venue.refreshesIn": "距刷新还有",

  "event.deposit": "入场押金",
  "event.heldBy": "由合约保管。",
  "event.notByOrganizer": "不经主办方之手。",
  "event.joinFor": "支付 {amount} 参加",
  "event.aboutThis": "创建一个有意义的活动",
  "event.details": "活动详情",
  "event.peopleGoing": "{n} 人要来",
  "event.onchainAttendance": "链上出席记录",

  "verify.title": "公开记录",
  "floor.title": "签到现场",
  "floor.notRegistered": "你还没有报名这个活动",
  "floor.notRegisteredBody": "押金是见证有分量的前提，所以这里只对交过押金的人开放。",
  "floor.goRegister": "回去报名",
  "floor.doorsOpenBody": "在那之前，你的码和别人的码都是活的，只是还不能提交。这个页面开着就行，时间到了会自己解锁。",
  "floor.countsPresent": "你已被判定到场。",
  "floor.scanAtLeastOne": "至少去扫一个人——光被别人作证不算数。",
  "floor.needMore": "还差 {n} 个",
  "floor.confirmedPresent": "全场已确认到场",
  "floor.room": "全场",
  "floor.howProve": "这凭什么能证明我在现场？",
  "floor.howProveBody": "签到时你花掉了门口屏幕上的一个码，那笔交易的时间戳是链盖的——这就是你进过这个房间的凭据。之后每扫一个人，又是一笔交易，同时给你们两个人记一分。没有任何人在中间审核。",
  "floor.vouchedByYou": "你为其作证",
  "floor.staleRead": "读不到合约，下面的数字可能是旧的。",
  "floor.localChain": "本地链——这里的延迟是本机出块时间，不是 Monad 的。",
  "events.closesIn": "{t} 后截止",
  "events.endsIn": "{t} 后结束",
  "events.finished": "已结束",
  "events.cancelled": "已取消",
  "events.settled": "已结算",
  "events.vouchesNeeded": "需要 {k} 个人作证才算到场",
  "events.sample": "示例",
  "events.sampleDetail": "这是一个示例活动。下面所有数字都是写死的,链上不存在这场活动——用来看页面长什么样。",
  "events.seeRealOnes": "看真正在办的活动 →",
  "events.sampleNote": "以下是活动展示出来的样子。这个合约上还没有人开过活动。",
  "events.createFirst": "创建第一个活动",
  "events.noMatchTitle": "这里还没有",
  "events.noMatchBody": "现在没有活动符合这个筛选。",
  "events.showAll": "显示全部",
  "events.signInForMine": "在任意活动里登录，就能看到你报过名的。",
  "events.sourceNote": "标题来自一个不持有任何资金的合约。押金在完全另一个地方。",
  "common.localChain": "本地链——交易是真的，钱是假的。",
  "common.noContract": "没有配置合约。",
  "common.signIn": "登录",
  "common.retry": "重试",
  "event.registered": "已报名",
  "event.snapshot": "活动状态",
  "event.tabAbout": "活动介绍",
  "event.tabAgenda": "日程安排",
  "event.tabVenue": "场地信息",
  "event.openMap": "在地图上看",
  "event.venueNote": "地点是主办方自己写的一行字,合约不核对它——到场是由在场的人互相证明的,不是由坐标证明的。",
  "event.tabRules": "验证规则",
  "event.tabFaq": "常见问题",
  "event.noBlurb": "主办方还没写介绍。",
  "event.methodTitle": "验证方式",
  "event.phaseOpen": "开始报名",
  "event.phaseAttest": "正在签到",
  "event.phaseClosed": "报名已截止",
  "event.phaseSettled": "已结算",
  "event.verifiedLabel": "已验证参与者",
  "event.whenLabel": "时间",
  "event.venueUnset": "主办方还没填地点",
  "event.vTilePeers": "在场的人互相扫,{k} 次就算到场",
  "event.vDoorTitle": "门口的码",
  "event.vDoorBody": "每 30 秒换一次,拍照没用",
  "event.vChainTitle": "写在链上",
  "event.vChainBody": "每一次作证都是一笔交易",
  "event.vPayTitle": "自动结算",
  "event.vPayBody": "合约照证明分钱,没人经手",
  "event.methodBody": "在场的人互相扫码作证。被 {k} 个人作证过,就算到场——没有主办方点名,也没有任何一个人的判断能决定结果。",
  "event.vouchesNeededLbl": "需要作证数",
  "event.minimumToRun": "最低成行人数",
  "event.confirmedPresentShort": "已确认到场",
  "event.spotsTaken": "已占名额",
  "event.walkInsOn": "接受现场报名",
  "event.walkInsOff": "不接受现场报名",
  "event.joinUntilClose": "活动结束前都可以加入",
  "event.registrationClosesAtDoors": "开场即停止报名",
  "event.doorsOpenIn": "{time} 后开场",
  "event.checkInOpenNow": "现在可以签到",
  "event.checkInClosed": "签到已结束",
  "event.today": "今天",
  "event.tomorrow": "明天",
  "event.yesterday": "昨天",
  "event.stakeAndRegister": "支付 {amount} 押金并报名",
  "event.staking": "提交中…",
  "event.full": "名额已满",
  "event.registrationClosed": "报名已截止",
  "event.youreIn": "报名成功。你的押金由合约保管，不在主办方手里。",
  "event.goToFloor": "进入签到现场",
  "event.openMyCode": "打开我的到场码",
  "event.signedInAs": "当前身份 {name}",
  "event.useDifferentAccount": "换一个账号",
  "event.chooseSignIn": "报名时再选择怎么登录。",
  "event.noWalletPlugin": "不需要装钱包插件。",
  "event.publicProof": "公开凭据",
  "event.publicProofSub": "每一次被采纳的作证都是一笔你能自己去查的交易",
  "myEvents.noneHosted": "你还没有办过活动",
  "myEvents.noneHostedBody": "从「新建活动」开始。没有审批，也没有上架费——押金直接进合约，你从头到尾都碰不到。",
  "organizer.yourEventsEmpty": "你还没有创建过活动。",
  "organizer.noVouchesYet": "还没有作证记录——等大家开始互扫，这里就会有数据。",
  "organizer.readOnly": "这个活动是 {who} 创建的，你只能查看。",
  "organizer.view": "查看",
  "verify.subtitle": "谁为谁作了证，钱又去了哪里。这里没有一个数字来自我们的数据库——全部由合约自己的事件重建。",
  "verify.graph": "作证关系图",
  "verify.arithmetic": "结算算式",
  "verify.everyVouch": "每一次作证 · {n} 笔交易",
  "verify.readingChain": "正在读取链上事件…",
  "verify.backToEvent": "返回活动",
  "venue.setupTitle": "会场信标屏",
  "venue.setupBody": "把创建活动时拿到的信标密钥粘贴到这里。",
  "venue.start": "启动显示",
  "venue.forgetKey": "清除这个密钥",
  "venue.beacon": "信标 {address}",
  "art.noJudge1": "没有",
  "art.noJudge2": "中央裁判",
  "home.searchPlaceholder": "搜索活动、地点或主办方…",
  "home.signIn": "登录 / 注册",
  "home.joinTitle": "我要参加活动",
  "home.hostTitle": "我要办活动",
  "strip.custodyTitle": "主办方不保管资金",
  "strip.custodyBody": "押金由智能合约托管",
  "strip.peerTitle": "同伴互证",
  "strip.peerBody": "在场的人互相证明",
  "strip.publicTitle": "公开可查",
  "strip.publicBody": "所有记录都在链上",
  "strip.fastTitle": "快速高效",
  "strip.fastBody": "通常几秒内完成确认",
  "nav.forOrganizers": "面向主办方",
  "home.builtOn": "基于 Monad",
  "home.fastFair": "快、公平、链上可查。",
  "home.headline1": "真实的人。",
  "home.playScene": "播放这段",
  "home.pauseScene": "暂停",
  "home.headline2": "真实的到场。",
  "home.script": "不用相信任何人，只需要验证事实。",
  "home.joinSub": "找找附近的活动",
  "home.hostSub": "创建一个活动",
  "stats.title": "Monad 让它实时发生。",
  "stats.finality": "0.6s",
  "stats.finalityLabel": "Monad 的最终性",
  "stats.cost": "0.026 MON",
  "stats.costLabel": "一次作证，按当前 gas 价",
  "stats.onchain": "链上",
  "stats.onchainLabel": "你可以自己查",
  "home.step4Title": "获得证明",
  "home.step4Body": "被判定到场的人拿回押金，再分掉缺席者留下的那部分。主办方没有任何一个函数能碰这笔钱。",
  "home.howTitle4": "从报名到获得证明，只需四步",
  "home.stepsOutroTitle": "真实的参与,带来真实的机会",
  "home.stepsOutroBody": "你的每一次参与,都会成为可验证的链上记录。这些记录不属于任何一个平台,它们属于你。",
  "home.howLink": "它如何工作？",
  "live.title": "正在发生",
  "live.events": "活动",
  "live.present": "到场人数",
  "live.pool": "奖金池",
  "home.featured": "精选活动",
  "home.viewAll": "查看全部",
  "home.noneYet": "这个合约上还没有活动。",
  "home.noneYetBody": "谁都可以办一场——没有审批这一步，而且主办方永远碰不到押金。",
  "footer.tagline": "不需要相信谁的出席证明。",
  "footer.source": "源码",
  "footer.contract": "合约",
  "home.howItWorks": "运作方式",

  "common.save": "保存",
  "common.gotIt": "知道了",
  "common.viewTx": "查看交易 ↗",
  "common.eventNumber": "活动 #{id}",

  "identity.checking": "正在检查这台设备…",
  "identity.noPrf": "这台设备存不了通行密钥。",
  "identity.noPrfEmail": "改用邮箱登录就行，什么都不用装。",
  "identity.noPrfWallet": "可以改用浏览器钱包参加。",
  "identity.noPrfNeither": "换成手机打开，或者装一个浏览器钱包。",
  "identity.continueEmail": "用邮箱继续",
  "identity.useBrowserWallet": "用浏览器钱包",
  "identity.continueWallet": "用我的钱包继续",
  "identity.why": "为什么？",
  "identity.whyBody1":
    "你的通行密钥服务不支持 WebAuthn 的 PRF 扩展——正是它让这个应用能在后台给你的到场码签名，而不用每十五秒验一次指纹。最常见的是 Chrome 桌面版自带的通行密钥；iPhone 的 iCloud 钥匙串、Android 的 Google 密码管理器都没问题。",
  "identity.whyBody2":
    "钱包这条路也能用一次签名派生出同样的密钥，但之后每作一次证都要你确认一次——而这正是通行密钥省掉的麻烦。",
  "identity.setUpTitle": "创建你的到场密钥",
  "identity.setUpBody":
    "只弹一次窗，就这一次。之后应用会在后台给你的码签名——不用每十五秒按一次指纹，没有助记词，不用装东西。",
  "identity.createKey": "创建我的密钥",
  "identity.haveOne": "我已经有了",
  "identity.useWallet": "用钱包",
  "identity.useEmail": "用邮箱",
  "identity.boundTo": "绑定到",
  "identity.signedInAs": "当前身份",
  "identity.wallet": "钱包",

  // 「充 MON 才能报名」：{what} 是动词，从调用处传进来。
  "funding.addMon": "充 MON 才能{what}",
  "funding.whatRegister": "报名",
  "funding.short":
    "你现在有 {have}，大约需要 {need}，还差 {short}。押金是你自己的钱，交给合约保管，没法由别人替你出——正因为如此，不到场才有代价。",
  "funding.sendTitle": "往你的地址转 MON",
  "funding.sendBody":
    "用别的钱包扫这个码，或者直接复制地址。任何能在 {chain} 上转账的方式都行——交易所提现、朋友转你、你自己的另一个钱包。",
  "funding.qrAlt": "你的地址二维码",
  "funding.topUp": "充值",
  "funding.topUpWalletNote":
    "刷卡充值走的是你登录用的那个账号，只在邮箱登录这条路上提供。用浏览器钱包的话，按你平时的方式买 MON，再转到上面这个地址。",
  "funding.localFund": "本地链——用",
  "funding.localFundEnd": " 给这个地址打钱。",

  "topup.cta": "用银行卡充值",
  "topup.opening": "正在打开…",
  "topup.submitted": "已提交。到账可能要几分钟——这个页面会自己更新。",
  "topup.done": "已充值。余额稍后会更新。",
  "topup.closed": "已关闭，没有充值。",
  "topup.soonTitle": "银行卡充值还没开通",
  "topup.soonBody1":
    "这里以后是刷卡付款的入口。现在还没开，原因不在我们这边：目前没有任何服务商把 MON 直接卖进钱包。MoonPay 在 Monad 上做过，但停掉了；Stripe 的可选目标里没有 Monad。",
  "topup.soonBody2":
    "在那之前，用上面那个地址——从交易所、从另一个钱包，或者让别人转给你。这条路现在就能走。",

  "error.walletRejected": "你在钱包里拒绝了这笔操作。",
  "error.walletUnauthorised": "钱包还没授权这个网站。重新连接后再试。",
  "error.walletNoNetwork": "你的钱包里没有配置这条网络。",
  "error.walletBusy": "钱包里还有一个请求没处理完——去看看是不是有待确认的弹窗。",
  "error.insufficientFunds": "这个钱包里的 MON 不够付这笔交易的 gas。",
  "error.noReason": "钱包拒绝了这笔操作，也没说原因。",
  "error.staleBeacon": "签到还没上链，门口的码就已经换了。再扫一次门口的屏幕。",
  "error.badBeacon": "这个门口的码是另一场活动的。",
  "error.notCheckedIn": "先在门口签到——扫一下现场的屏幕，只需要一次。",
  "error.alreadyCheckedIn": "你已经签到过了，去扫人吧。",
  "error.staleCode": "对方的码还没上链就过期了。让他把手机拿稳，再扫一次。",
  "error.badCode": "这个码没能通过验证，可能是另一场活动的。",
  "error.pairAlreadyUsed": "你们俩已经互相作过证了。扫一次就同时算两个人的。",
  "error.selfAttestation": "这是你自己的码——得扫别人的。",
  "error.notRegistered": "你们其中一个没有报名这场活动。",
  "error.windowOpen": "签到还没开始。",
  "error.windowClosed": "这场活动的签到已经结束。",
  "error.wrongStatus": "这场活动已经不开放了。",
  "error.alreadyRegistered": "你已经报过名了。",
  "error.quorumNotMet": "报名人数太少，这场活动开不成。",
  "error.badParams": "合约拒绝了这组参数。最常见的两种:成行最低人数没有大于需要作证数;或者开场时间已经过了而没有接受现场报名。回上一步检查这几个数。",
  "error.fallbackPending": "结算在等兜底窗口过去。",

  "vouch.landedIn": "上链耗时",
  "vouch.you": "你",

  "registered.inContract": "{amount} 已经进了合约",
  "registered.body":
    "不在主办方的钱包里。等现场有人证明你到过，押金就会回到你手上——还会带上没到场的人留下的那一份。",
  "registered.next": "接下来：",
  "registered.opensIn": "{t} 后开始签到",
  "registered.openNow": "现在就可以签到",
  "registered.andNeedOne": "，还需要 1 个人为你作证。",
  "registered.andNeed": "，还需要 {n} 个人为你作证。",
  "registered.viewTx": "查看报名交易 ↗",
  "registered.title": "报名成功 🎉",
  "registered.sub": "{amount} 已经进了合约,不在主办方的钱包里。等现场有人证明你到过,押金就回到你手上——还会带上没到场的人留下的那一份。",
  "registered.doorsLabel": "多久后开始签到",
  "registered.vouchesLabel": "需要几个人作证",
  "registered.keepBrowsing": "继续看看别的活动",

  "payout.paidOut": "已到账",
  "payout.extraPre": "退还你的 {amount} 押金，另外还有",
  "payout.extraPost": "是没到场的人留下的。",
  "payout.noExtra": "退还你的 {amount} 押金。报名的人全都到了，没有被没收的押金可分。",
  "payout.noApproval": "没有人批准过这笔钱。窗口一关，怎么分就定死了——按谁为谁作过证算。",
  "payout.seeTx": "看这笔交易 ↗",

  "handoff.title": "把门口那块屏幕装起来",
  "handoff.body":
    "用要摆在入口的那台设备扫一下——备用手机、平板、笔记本都行。扫完直接打开会场屏，密钥已经装好了。",
  "handoff.qrAlt": "会场屏设置码",
  "handoff.sameDevice": "已经在那台设备上了？不用扫，直接从这里打开。",
  "handoff.keyWarning":
    "这个码里装的就是密钥，请当成密钥本身对待：它只能给这场活动签会场码，别的什么都做不了，签到一结束就彻底失效。",
  "venue.openDisplay": "打开会场屏",

  "listing.whatPeopleSee": "别人在活动列表里看到的",
  "listing.editHint": "随时可以改。它和押金分开存放，改它动不到钱。",
  "listing.noTitleHint":
    "这场活动还没有标题，在活动列表里只会显示成一个编号。补一个标题只花一点点 gas，没有别的代价。",
  "listing.saved": "已保存。活动列表几秒内就会更新。",
  "listing.saving": "保存中…",
  "listing.settingUp": "正在准备活动描述…",
  "listing.title": "标题",
  "listing.titleHint": "例如：周四读书会",
  "listing.noTitleWarn": "不填标题也能建,只是它在活动列表里只会显示成一个编号。",
  "listing.description": "描述",
  "listing.blurbPlaceholder": "给谁办的、会发生什么、在哪里。",
  "listing.venue": "地点",
  "listing.venueHint": "写清楚地方，比如「开元空间 · 新加坡」或者「线上」。",
  "listing.online": "线上",
  "listing.onlineEvent": "线上活动",
  "listing.tags": "标签（选填）",
  "listing.cover": "活动封面图",
  "listing.coverUrlPlaceholder": "或者贴一个图片链接",
  "listing.coverBroken": "这个链接打不开,或者它不是一张图。",
  "listing.coverNotUrl": "要一个完整的链接,http:// 或 https:// 开头。",
  "listing.tagsHint": "逗号隔开,比如「读书会, 线下, 每周」。搜索时能搜到。",
  "listing.link": "链接（选填）",
  "listing.linkHint": "如果有更详细的页面",
  "listing.addTitle": "加个标题",

  "event.runDevChain": "先运行",
  "event.runDevChainEnd": "，然后重启开发服务器。",
  "event.cantReach": "现在读不到合约——{why}",
  "event.signedInLabel": "当前身份",
  "event.walletBalance": "钱包 {address} · 余额 {balance}",
  "event.revertedOnChain": "报名交易在链上被回滚了。",
  "event.pageName": "活动详情",
  "event.joinUntilTime": "{time} 之前都可以加入",
  "event.howTitle": "到场是怎么证明的",
  "event.howSub": "门口扫一次，剩下的慢慢来",
  "event.howP1":
    "进场时扫一下门口那块屏幕。它的码每三十秒换一次，签到会立刻把它花掉，于是链本身记下了你走进来的时刻——这一点，在另一个城市的人伪造不了。",
  "event.howP2":
    "之后现场就再没有任何倒计时了。认识人、聊天，什么时候想扫就扫。每个人的码每十五秒换一次，截图转给别人，过两轮就作废了。",
  "event.howP3":
    "而且要被算作到场，你自己也得为别人作过证——这又要求你签到过。每一个最终算作到场的账号，都是从门口进来的。朋友替你远程刷不进来。",
  "event.depositTitle": "押金会怎么样",
  "event.depositSub": "来了，就能连本带利拿回去",
  "event.depositP1": "只要到场，押金原样退给你，还能分到没到场的人留下的那一份",
  "event.surplusAbout": "——按目前人数",
  "event.surplusAtCount": "左右",
  "event.depositP1End": "。",
  "event.depositP2": "不来，你的押金就归来了的人。",
  "event.depositP3": "如果报名人数太少、活动开不成，所有押金全额退回——包括你的。",
  "event.signInSheetTitle": "你想怎么登录？",
  "event.signInSheetSub": "任选一种，只需一次。什么都不用装。",
  "event.signedInPressAgain": "已经登录了——再按一次报名。",

  "organizer.showing": "正在看",
  "organizer.awaitingSettlement": "等待结算",
  "organizer.nothingHostedBody":
    "点「创建活动」就行。没有审批，也没有上架费——押金进的是合约，你从头到尾碰不到。",
  "organizer.pulsePast": "这些作证是怎么来的，从早到晚。",
  "organizer.pulseAria": "{n} 次作证，从最早到最近：{bars}",
  "organizer.vouchOne": "1 次作证",
  "organizer.vouchMany": "{n} 次作证",
  "organizer.overTheLast": "，来自最近 {t}",
  "organizer.logsUnavailable": "刚才没能读到作证记录。",
  "organizer.payoutsDetail":
    "这个合约里没有任何一个函数能把钱付给主办方，报名一开始，参数你也改不了。窗口关闭后，任何人——或者一个定时任务——都可以触发分账，而怎么分早就定好了。",
  "organizer.footNote":
    "这个页面上的每一项都是从合约里读出来的。主办方这个角色是用来描述一场活动的，不是用来决定它的结果的。",
  "organizer.loadingEvent": "正在加载活动…",
  "organizer.checkingInEndsIn": "签到中 · {t} 后结束",
  "organizer.stillWalkIns": " · 仍接受现场报名",
  "organizer.registeringUntil": "报名开放到 {time}",
  "organizer.waitingDoors": "报名已截止——等开场",
  "organizer.checkInClosed": "签到已结束",
  "organizer.depositPer": "每人押金",
  "organizer.ofPlaces": "{n} / {cap} 个名额",
  "organizer.vouchesEach": "{n} · 每人需 {k} 次作证",
  "organizer.runsIfAtLeast": "成行最低人数",
  "organizer.nRegister": "{n} 人报名",
  "organizer.statusOpen": "进行中",
  "organizer.statusCancelled": "已取消——全额退款",
  "organizer.venueNote": "——门口那块屏幕，密钥就记在那台设备的浏览器里。也可以去看",
  "organizer.venueNoteEnd": "。",
  "organizer.publicRecord": "公开记录",
  "organizer.fallbackTitle": "兜底签到已解锁",
  "organizer.fallbackBody":
    "现场没能凑够互证的人——到场的人太少，作证链没建起来。你可以确认实际到场的是哪些人。这是唯一一处你的说法算数的地方，而且它依然不会让你拿到任何一分钱。",
  "organizer.fallbackHint":
    "把要确认的地址粘进来，一行一个。（房间运转正常时，这一整块根本不会出现，因为合约会直接拒绝这个调用。）",
  "organizer.noValidAddresses": "没有有效的地址。",
  "organizer.confirming": "确认中…",
  "organizer.confirmAttendees": "确认这些到场者",

  "create.subtitle": "一步一步来，高级选项需要时才出现。",
  "create.creating": "创建中…",
  "create.savingDescription": "正在保存描述…",
  "create.reverted": "createEvent 被回滚了",
  "create.descriptionFailed": "活动创建成功，但描述没保存上：{why}",
  "create.createdTitle": "活动 #{id} 已创建",
  "create.beaconBody":
    "把下面这把会场信标密钥保存好，装到门口那台设备上。它负责给不断变化的会场码签名——没有它，谁也证明不了自己进过这个房间。",
  "create.beaconWarning":
    "只显示这一次。它不持有任何资金，但一旦丢了，会场屏就签不了名——而且合约只允许在开场之前换密钥。",
  "create.descriptionFailedNote":
    "活动本身没问题——押金、签到、结算都不依赖它。什么时候想补上这些文字，都可以在总览页补。",
  "create.backToEvents": "返回你的活动",
  "create.stepAbout": "介绍",
  "create.stepVerify": "验证规则",
  "create.stepMoney": "押金与名额",
  "create.stepPublish": "发布活动",
  "create.nextStep": "下一步：{name}",
  "create.verifyTitle": "怎么确认一个人真的到过",
  "create.verifySub": "这几项一旦开始报名就锁死——对你也一样。",
  "create.methodPeer": "同伴互证",
  "create.methodPeerBody": "在场的人互相扫码作证。没有主办方点名,也没有任何一个人的判断能决定谁到没到。",
  "create.moneyTitle": "押金与名额",
  "create.moneySub": "押金由合约保管,不进你的钱包。人到了就退回去,没到的那份分给到场的人。",
  "create.publishTitle": "发布前再看一眼",
  "create.publishSub": "下面这些一旦创建就改不了了,再看一眼。",
  "create.untitled": "(没填标题)",
  "create.lockedNote": "按下去会发起一笔交易。活动一旦建好,押金、名额、作证数、时间窗口全部锁死。",
  "listing.tagAdd": "添加标签",
  "listing.tagRemove": "删掉标签 {tag}",
  "listing.tagPlaceholder": "比如 读书会",
  "common.yes": "接受",
  "common.no": "不接受",
  "create.stepRules": "规则",
  "create.aboutTitle": "创建一个有意义的活动",
  "create.aboutSub": "填写活动的基本信息，让更多人了解并参与你的活动。",
  "create.next": "下一步 · 规则 →",
  "create.rulesTitle": "规则",
  "create.rulesSub": "报名一开始就锁死——对你也一样。",
  "create.deposit": "押金（MON）",
  "create.capacity": "名额",
  "create.quorumHint": "必须大于作证数",
  "create.vouchesNeeded": "需要作证数",
  "create.kHint": "3 是个不错的默认值",
  "create.doorsMins": "多久后开场（分钟）",
  "create.doorsHint": "什么时候开始签到",
  "create.runsMins": "持续多久（分钟）",
  "create.startAt": "开场时间",
  "create.saveDraft": "保存草稿",
  "create.draftSaved": "已存 ✓",
  "create.startHint": "用你自己所在时区的时间填。到点之后门口那块屏才开始接受扫码。",
  "create.startInPast": "这场活动已经结束了,把开场时间或持续时间改一下。",
  "create.badDeposit": "押金要大于 0。",
  "create.badCapacity": "名额要填一个大于 0 的整数。",
  "create.badK": "需要作证数要填一个大于 0 的整数。",
  "create.badQuorum": "成行最低人数要填一个大于 0 的整数。",
  "create.quorumOverCapacity": "成行最低人数不能超过名额。",
  "create.quorumUnderK": "成行最低人数要大于需要作证数——房间里得有足够的人互相作证。",
  "create.badStart": "开场时间填一下。",
  "create.badRuns": "持续时间要大于 0 分钟。",
  "create.openPastNoWalkIns": "开场时间已经过了,而你没有接受现场报名——这样没人来得及报名。要么把开场时间往后挪,要么勾上「接受现场报名」。",
  "create.runsHint": "签到开放多长时间",
  "create.walkIns": "接受现场报名",
  "create.walkInsOnBody":
    "开场之后也还能报名——一个房间在当晚临时吸引来的人，往往正是值得留下的那些。",
  "create.walkInsOffBody": "开场即停止报名。经典 RSVP：要么提前定，要么就别来。",
  "create.noCustodyNote":
    "你不用出钱，也不会因此拿到任何动用资金的权力。押金进的是合约；怎么分，由谁为谁作过证决定。",

  "deploy.escrowWarning":
    "当前托管合约上的所有活动都会被留在原地。那边的押金还能用旧地址领取，但这个应用不会再指向它们。",
  "deploy.dirTitle": "这套部署只需做一次",
  "deploy.dirBodyPre": "活动现在显示成",
  "deploy.dirBodyPost":
    "，而不是名字。标题存在第二个合约里，这样保管押金的那个合约永远不必为了存文字而改动——部署一次，之后每场活动都能自己写介绍。",
  "deploy.dirDone": "已部署。没有要配置的东西——地址是从字节码推出来的，每个构建都能找到它。",
  "deploy.dirTx": "部署交易",
  "deploy.dirBusy": "部署中…",
  "deploy.dirCta": "部署目录合约",
  "deploy.dirGas": "大约 0.2 MON。",
  "home.redirecting": "正在带你去这个活动…",
  "home.howItWorksSub": "一笔押金、一屋子人，以及一个照着这屋子自己给出的证据来结算的合约。",
  "home.step1Title": "报名活动",
  "home.step1Body": "押金是你占住位置的方式。钱进的是合约，主办方从头到尾碰不到。",
  "home.step2Title": "现场签到",
  "home.step2Body": "进场时扫一次现场那块屏。这一下是单独一笔交易，由链给你的到达时间盖戳，不是谁说了算。",
  "home.step3Title": "完成验证",
  "home.step3Body": "扫你真正遇到的人，一次互扫两个人同时得分。对方的码 15 秒一换，转发截图没有用。",
  "home.custodyNote": "创建活动的人没有任何一个函数能放款、能扣款、能收款，一个 wei 都不行。这不是一句承诺，是根本没有那扇门。",
  "home.bothRoles": "同一个账号两边都能做——这是两个入口，不是两种人。谁都可以办活动，没有审批这一步。",
  "home.readPublicRecord": "查看公开记录",
  "venue.eyebrow": "会场信标",
  "venue.setupEyebrow": "一次性配置",
  "venue.setupHeadline": "载入会场信标",
  "venue.credentialNote": "信标密钥是一份凭据。它只留在这台设备上，配置完成后会立刻从地址栏抹掉。",
  "venue.keyHoldsNoFunds": "这个密钥不持有任何资金，也永远动不了钱，它只负责签名。只存在这个浏览器里，不会发往任何地方。",
  "venue.notAKey": "这看起来不像私钥（应该是 64 个十六进制字符）。",
  "venue.invalidKey": "这个密钥无效。",
  "verify.openOnExplorer": "在区块浏览器打开",
  "verify.roomDecided": "这是这屋子人自己决定的",
  "verify.eachLine": "每一条连线都是一次被采纳的真实作证。",
  "verify.settlement": "结算",
  "verify.settlementRow": "结算",
  "verify.eachReceives": "每位被确认到场的人拿到",
  "verify.eachWouldReceive": "每位被确认到场的人将拿到",
  "verify.nobodyConfirmedYet": "目前还没有人被确认到场。",
  "verify.depositPlusShare": "押金 {deposit} + 缺席者分成 {share}",
  "verify.confirmedPresent": "{n} 人确认到场",
  "verify.getDepositBack": "拿回押金",
  "verify.neverConfirmed": "{n} 人未被确认",
  "verify.forfeit": "没收 {amount}",
  "verify.settledNote": "结算那一刻由合约钉死。除数之后不会再变，所以这个池子永远不可能超额分配。",
  "verify.settlementTx": "结算交易",
  "verify.projectedNote": "这不是最终数字。如果没有人能被确认到场，合约会把每一笔押金原样退回，而不是给出一个站不住脚的判定——那种情况下主办方同样一分钱拿不到。",
  "verify.noOrganizerApproved": "没有任何主办方批准过这件事。",
  "verify.payoutFollowsGraph": "结算金额跟着窗口关闭那一刻的作证图走。",
  "verify.blocks": "区块 {from}–{to}",
  "verify.viaEnvio": "作证关系图由 Envio HyperIndex 索引。",
  "verify.viaLogs": "作证关系图直接从合约日志读取——索引服务当时连不上。",
  "verify.noPayoutFunction": "这个合约里没有任何一个函数会付钱给主办方。去看源码：claim 的每一个分支都只付给 msg.sender，而且只有报过名的参与者能走到那里。",
  "identity.creatingKey": "正在生成你的密钥…",
  "identity.unlocking": "正在解锁…",
  "identity.waitingWallet": "等待钱包响应…",
  "identity.signInFailedLoad": "登录组件没能加载——{why}。这是邮箱登录的代码本身没下来，通常是广告拦截器或隐私插件把它拦了，也可能是页面从上一个版本一直开着没刷新。先刷新页面；如果还不行，在插件里把这个站点放行。",
  "identity.signInBlocked": "登录组件没加载出来。这个浏览器上可能有东西在拦 privy.io——广告拦截器、隐私插件，或者严格的追踪保护设置。把这个站点放行，或者改用浏览器钱包。",
  "identity.openingSignIn": "正在打开登录…",
  "identity.noWallet": "没有找到浏览器钱包。",
  "graph.confirmed": "已确认到场",
  "graph.neverConfirmed": "报了名，但没被确认",
  "graph.numberMeans": "数字 = 收到的作证数",
  "graph.present": "到场",
  "graph.presentFallback": "到场（主办方兜底判定）",
  "graph.forfeited": "押金没收",
  "graph.notYet": "还没被确认",
  "floor.alreadyCheckedIn": "你已经签到过了——继续找人的二维码就行。",
  "floor.checkedInFlash": "签到完成。现在去扫人吧，不用急，这个整晚有效。",
  "deploy.dirBody": "活动的标题和封面存在另一个合约里。它还没建起来,点一下就好——只需要做这一次,之后所有人共用。",
  "event.noSuchTitle": "这里还没有活动",
  "event.noSuchBody": "这个合约上没有这个编号的活动。要么还没创建，要么这个链接指向的是另一份部署。没有任何损失——这里本来就什么都没有。",
  "home.closeTitle": "这里的每一句话你都不用信我们",
  "home.closeBody": "合约在 Monad 测试网上，源码已验证。每一笔押金、每一次作证、每一次结算，都是一笔你不用问我们就能自己读到的交易。",
  "gate.orgTitle": "办一场活动会发生什么",
  "gate.orgBody": "你把规则设一次，之后由合约执行。整个过程里没有任何一步是由你来决定谁到了场。",
  "gate.org1Title": "你定规则",
  "gate.org1Body": "押金、名额、几个人作证算到场、什么时候开场。报名一开始，这些谁都改不了——包括你。",
  "gate.org2Title": "人到场，互相证明",
  "gate.org2Body": "他们扫你门口那块屏签到，然后互相作证。你负责把屏幕摆出来，但你不给任何人点名。",
  "gate.org3Title": "合约自己结算",
  "gate.org3Body": "被确认到场的人拿回押金，再分掉缺席者留下的。你一分钱拿不到——因为合约里根本没有能付给你的函数。",
  "gate.floorTitle": "到了现场你要做的事",
  "gate.floorBody": "扫两次码，然后等。剩下的事在链上自动发生，不需要谁批准。",
  "gate.floor1Title": "在门口签到",
  "gate.floor1Body": "把摄像头对准现场那块屏。进门时扫一次就够，整晚有效。",
  "gate.floor2Title": "扫你遇到的人",
  "gate.floor2Body": "扫一次，你们两个人同时得分。不用急——对方的码 15 秒换一次，下一个已经在屏幕上了。",
  "gate.floor3Title": "把押金拿回去",
  "gate.floor3Body": "被足够多的人作证之后，你就算到场。窗口关闭时，你拿回押金，外加缺席者留下的那部分里属于你的一份。",

  "scan.hintPeer":
    "把对方的手机拿近一点，让码占满大半个画面。码每 15 秒换一次——就算扫到一半过期了，下一个也已经在屏幕上了。",
  "scan.hintVenue":
    "门口那块屏上的码每 30 秒换一次。这个码会直接发到链上，所以要对着屏幕本身扫——不能扫照片。",
  "scan.cameraDenied": "摄像头权限被拒绝了。",
  "scan.cameraFailed": "摄像头打不开。",

  "floor.notPeerProofCode": "这不是 PeerProof 的码。",
  "floor.ownCode": "这是你自己的码——你要扫的是别人的。",
  "floor.codeFailedVerification": "这个码没通过验证。",
  "floor.venueCodeMalformed": "这个场地码格式不对。",
  "floor.checkInOpensIn": "码没问题——签到还有 {time} 开始。",
  "floor.checkInClosed": "码本身没问题，但这场活动的签到已经结束了。",
  "floor.checkInReverted": "签到在链上被回滚了。请重新扫一次门口那块屏。",
  "floor.attestReverted": "这次作证在链上被回滚了。",
  "floor.settleEvent": "结算这场活动",
  "floor.yourDepositBack": "拿回你的押金",
  "floor.shareOfForfeited": "缺席者押金中你的一份",

  "timeline.whatParticipants": "参与者会经历什么",
  "timeline.nowRegistration": "现在 · 报名中",
  "timeline.doorsOpen": "开场",
  "timeline.inTime": "还有 {time}",
  "timeline.eventEnds": "活动结束",
  "timeline.afterTime": "{time} 之后",
  "timeline.walkInsNote": "填满的这一段是还能报名的时间——开了现场报名，那就是整场活动。",
  "timeline.noWalkInsNote": "一开场就停止报名，之后谁也进不来。",

  "bridge.settingUpKey": "正在生成你的密钥…",

  "graph.nobodyRegistered": "还没有人报名。",
  "graph.noVouchesYet": "还没有连线——每有一个人扫了另一个人，就多一条。",

  "verify.statVerified": "确认到场",
  "verify.statProofs": "互相作证次数",
  "verify.statSettled": "已在链上结算",
  "verify.statPending": "尚未结算",
  "verify.graphLabel": "作证关系图：{people} 人，{proofs} 次被采纳的作证",
  "verify.inspectHint": "每一条连线都是一笔交易。点一条线，就能打开它。",
  "verify.inspectVouch": "{from} 为 {to} 作了证",
  "verify.whoWasThere": "当时这屋子里有谁",
  "verify.showAll": "展开全部 {n} 条",
  "verify.showLess": "收起",
};
